### ISSUE TITLE
Dangerous assignment should throw error

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#105]
Assignment expressions are currently safe only if they are to the global object (which is threaded through via the store). Assignments to non-global should throw an error (or at least warning). (I think they used to, but this seems to have been lost at some point.)

For example:
~~~
var a = [1,2,3]
a[1]=0
a
~~~

Note: alternatively, we could do the work of detecting assignment and handling it properly via the store... This is not totally straightforward because of scope.

**Comment by null-a** [comment]
@ngoodman I've reinstated the error we had previously. Are you happy to close this?

**Comment by ngoodman** [comment]
yes, thanks!
