### ISSUE TITLE
incorrect acceptance probability using MH with custom proposer 

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#115]
Suppose we have the following ERP generator, which assigns uniform probability to all integers between 1 and N. It has a custom proposer that suggests a very small subset of those integers with uniform probability. (Yes, this is a ridiculous ERP, but the same issue arises in more useful, complex cases).

```
var makeERP = function(maxNum) {                                   
  var mySampler = function(){                                   
        return Math.floor(Math.random * maxNum);                   
  };                                                             
  var myScorer = function(params, val){                         
        return Math.log(1/maxNum);                                 
  };                                                             
  var myProposer = new ERP(                                      
        function sample(params) {                                  
            var intervalWidth = Math.floor(maxNum / 10);           
            return Math.floor(Math.random() * 10 * intervalWidth); 
        },                                                         
        function score(params, proposedVal) {                      
            return Math.log(1/10);                                 
        }                                                          
  );                                                             
  var erp = new ERP(mySampler, myScorer,                       
                      {proposer: myProposer});                     
  return erp;
};

module.exports = {                                                                      
    makeERP : makeERP                                                                   
}      
```                                                                                 

Suppose we use this in a very simple model, like the following:

```
var myERP = customProposer.makeERP(10000);
                                        
var model = function() {                
    var mat = sample(myERP);            
    return mat;                         
};                                      
                                        
MH(model, 10, true);      
```

We expect that it would uniformly sample 10 values from the proposer distribution, since all samples have the same score under the base ERP, and the proposer is symmetric.

When we run this at the command line, we see that after the first sample, all proposals are rejected. When we print out the details of mh.acceptProb(), we see that it's using the custom proposer's scorer to compute the forward probability but the original ERP's scorer to compute the backward probability. Because the forward probability is so much larger, the acceptance probability is about 0.0001 (and this obviously gets smaller as the maxValue we use increases).

This seems to be a bug in the integration of custom proposers into MH -- both the forward and backward probabilities should use the custom proposer scores.

**Comment by stuhlmueller** [comment]
First, two minor comments:

There is a small bug in the example: Math.random should be Math.random():

    var mySampler = function(){                                   
      return Math.floor(Math.random() * maxNum);                   
    };

Also, the third parameter in the MH call is now burn-in, so let's change the call:

    MH(model, 10, 0, true);

Then, let's adjust the custom proposer so that we can actually explore the full support of the ERP:

    var myProposer = new ERP(                                      
      function sample(params) {
        var prevVal = params[1];
        if (prevVal == (maxNum - 1)){
          return flip() ? prevVal : (prevVal - 1);
        } else if (prevVal == 0) {
          return flip() ? 0 : 1;
        } else {
          return flip() ? (prevVal + 1) : (prevVal - 1);
        }
      },                                                         
      function score(params, proposedVal) {                      
        return Math.log(1/2);
      }                                                          
    );

We see that the bug is still present:

    $ webppl customProposer.wppl --require-js ./customProposer.js
    Processing customProposer.wppl
    Acceptance prob: 1
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance prob: 0.0002000000000000002
    Acceptance rate: 0.1
    Number of samples: 10
    
    * Program return value:
    
    ERP:
        4833: 1

The acceptance probability for each of the proposals should be 1.

The cause of this issue is that, on the first execution, `forwardChoiceScore` is set to `erp.score(params, val)` (because it's sampled from the prior). For the next sample, when we compute the acceptance probability, we use this `forwardChoiceScore` if no `reverseChoiceScore` is found. Why aren't we finding this `reverseChoiceScore` despite our custom proposer? It seems that there is a bug in the acceptance probability calculation:

    oldTrace.slice(regenFrom).map(function(s) {
      var nc = findChoice(trace, s.name);
      var reverseChoiceScore = (s.reverseChoiceScore !== undefined) ? s.reverseChoiceScore : s.forwardChoiceScore;      
      bw += (!nc || !nc.reused) ? reverseChoiceScore : 0;
    });

We are looking at the `reverseChoiceScore` of the old trace, but we should be looking at `nc.reverseChoiceScore`. If we change this, our results look as expected:

    $ webppl customProposer.wppl --require-js ./customProposer.js
    Processing customProposer.wppl
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance prob: 1
    Acceptance rate: 1
    Number of samples: 10
    
    * Program return value:
    
    ERP:
        4099: 0.2
        4100: 0.2
        4101: 0.2
        4102: 0.2
        4098: 0.1
        4103: 0.1

See [fix-custom-proposer-acceptance](/probmods/webppl/tree/fix-custom-proposer-acceptance) branch for the change.
