### ISSUE TITLE
Resample in particle filter (+ rejuv) if importance distributions are used without factors

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#120]
Currently, we only resample at factors, which means that we don't resample at all if there are no factors. In the presence of importance distributions, all weights won't be equal even if there are no factors. So either we need to have an extra resampling step in this situation, or take the weights into account when we construct the final histogram.

**Comment by null-a** [comment]
Am I right in thinking that in the case of rejuvenation accounting for the weights in the histogram won't be sufficient, and that we should re-sample before the final rejuvenation? (Otherwise we're applying the MH kernel to particles from the wrong distribution?)

**Comment by stuhlmueller** [comment]
Sounds right. (I'm not entirely sure that a scheme where you just account for the weights and don't resample couldn't still be correct, but even if that were the case, it would be less efficient, since you'd only have few particles in the high-probability region of the space.)
