### ISSUE TITLE
Allow control over where MH proposals are made

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#125]
I added `setProposalBoundary` in 01ffca685058381fd6f8cca6b60aa202d7725827 so that SMC rejuvenation proposals can be restricted to more recent ERPs, but it would be preferable to have more general mechanisms for controlling where proposals are made.

**Comment by null-a** [comment]
Is this a duplicate of #101?

**Comment by stuhlmueller** [comment]
Ha, yes. Apparently I want this very much. :-)
