### ISSUE TITLE
Make web visualizations work on the command line

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#130]

**Comment by hawkrobe** [comment]
I believe @iffsid suggested [node-canvas](https://github.com/Automattic/node-canvas) for this, which would allow you to keep the same d3 visualization functions.

**Comment by null-a** [comment]
Noah suggested we might want "enough to make svg/pdf file that can be viewed in browser?"

**Comment by longouyang** [comment]
This is working as of probmods/webppl-viz@385186e06b65dc47d19c2d1786913d590ddad8c4
