### ISSUE TITLE
Underflow from common prior: Gamma(0.001,0.001)

### ISSUE THREAD

**Issue by mhtess** [probmods/webppl#132]
A common prior used in Bayesian Data Analysis is Gamma(0.001,0.001). Here is it from Lee & Wagenmakers:

>The practice of assigning Gamma􏰂(0.001, 0.001) priors on precision parameters is theoretically motivated by scale invariance arguments, meaning that priors are chosen so that changing the measurement scale of the data does not affect inference. The invariant prior on precision λ corresponds to a uniform distribution on log σ, that is, p (σ2) ∝ 1/σ2, or a Gamma􏰂a → 0, b → 0􏰃 distribution. This invariant prior distribution, however, is improper (i.e., the area under the curve is unbounded), which means it is not really a distribution, but the limit of a sequence of distributions (see Jaynes, 2003). WinBUGS requires the use of proper distributions, and the Gamma(􏰂0.001, 0.001)􏰃 prior is intended as a proper approximation to the theoretically motivated improper prior. This raises the issue of whether inference is sensitive to the essentially arbitrary value 0.001, and it is sometimes the case that using other small values such as 0.01 or 0.1 leads to more stable sampling in WinBUGS. (Lee & Wagenmakers, *Bayesian Cognitive Modeling*, 2014, Chapter 4, Box 4.1)

In WebPPL,  `var lambda = gamma(0.001,0.001)` returns `0` within just a few samples.

**Comment by null-a** [comment]
WebPPL's `gamma` is parameterised by shape and scale, so assuming `a` and `b` are shape and rate I guess you'd want `gamma(0.001, 1/0.001)`?

Sampling from this still lead to lots of samples of exactly zero, so perhaps there's still underflow. (Incidentally numpy doesn't do any better with these parameters.)

I tried tweaking the parameters a little and noticed that e.g `gamma(0.01, 1e6)` gives more reasonable looking results.

**Comment by longouyang** [comment]
It looks like, for parameter values like shape = rate = 0.001, the probability density increases without bound as we approach x = 0. So this is indeed a problem of underflow; I propose that we return `Number.MIN_VALUE` whenever the sampled value is 0.

In addition, I suggest that we log a warning to the screen whenever we correct for underflow. If the parameters are such that most of the mass lies below `Number.MIN_VALUE`, the user will get flooded with such warnings, giving a stronger indication that something is wrong.

Thoughts?

**Comment by stuhlmueller** [comment]
Printing a warning is a good idea.

I'm not sure about the `MIN_VALUE` trick. If the actual sampled value is closer to `0` than to `MIN_VALUE` (which is `5e-324`), it feels wrong to return `MIN_VALUE`. Are there real situations where one might want to use a gamma with such extreme parameters? If yes, maybe it would be better to provide a specialized `logGamma` ERP? If no, can we analytically compute how much mass there is below `MIN_VALUE` and throw an error if it's not tiny?
