### ISSUE TITLE
Opaque MH acceptance probability

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#145]
Our acceptance probability calculation (both `acceptProb` and `MH.prototype.sample`) is difficult to reason about. We should refactor it so that it's clearer that it is correct.

**Comment by null-a** [comment]
Having fewer copies of `acceptProb` will also be useful. See #64.

**Comment by stuhlmueller** [comment]
A while ago, I started refactoring `sample` and `acceptProb` in 0cd680ef20c0bd70c458740984e2ad0198a59d46. This isn't quite right as it stands (it suffered from the bug in #115, and probably from others), but maybe some approach along these lines could work.

**Comment by null-a** [comment]
I was forced to [refactor the acceptance calculation](https://github.com/null-a/webppl/blob/d7fb357e147c349051850d2d2a256ae2eeef9911/src/inference/mhkernel.js#L78) when I added drift proposals to the version of MH I'm working with as part of #64. I think it's an improvement, I'd be interested what other people think.

**Comment by stuhlmueller** [comment]
Yes, something like this is going to be much easier to understand!

On the current proposal: What is the intended meaning of `q`? Is it: "Compute the probability that, given that we're starting from `fromTrace` and making a proposal to the r-th choice, we end up with `toTrace`?". If that's the case, we should assign probability 0 to reused choices (even if these numbers would cancel out if you didn't do this), as pointed out in your TODO.

**Comment by null-a** [comment]
Closed by #169.
