### ISSUE TITLE
Add test for MH with custom proposer

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#147]
While reviewing #144 I think I spotted another bug the MH acceptance probability calculation.

I have tests that demonstrate the problem and a crude fix [here](https://github.com/null-a/webppl/commit/dbc8f2718fb7534fe9890905f782f24c85a0397c), I'll work on something better.

I've tried to explain the problem in this [comment](https://github.com/null-a/webppl/commit/dbc8f2718fb7534fe9890905f782f24c85a0397c#diff-e6a81eea28f03b04580fee336cee7895R95).

**Comment by stuhlmueller** [comment]
Yeah, that's a bug! Your explanation and fix makes sense to me. Can you create a pull request with a test that catches this and with your current fix (or a slight refactor)? We'll refactor this more generally as part of #145.

**Comment by null-a** [comment]
This was fixed by #169.

I still need to add a test which should be easier after #119.
