### ISSUE TITLE
Preload editor on webppl.org with interesting examples

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#148]
To be added in [initializeEditor.js](/probmods/webppl/blob/gh-pages/initializeEditor.js).

We may want to refactor how we are specifying the examples (i.e., not as a list of strings).

**Comment by mhtess** [comment]
Can I add some simple BDA examples so my class can use the page on the first day?

**Comment by hawkrobe** [comment]
it'd be nice if there were a sidebar or menu with a list of examples so you could try out the ones you're interested in without it being too cluttered
