### ISSUE TITLE
Node name conflict in Ubuntu

### ISSUE THREAD

**Issue by bergen** [probmods/webppl#15]
It appears that webppl will not run off the shelf in Ubuntu. There is a name conflict between node.js and a separate package, ax25-node. More details: https://groups.google.com/forum/#!topic/nodejs/Z8F8uDXY8XE

**Comment by stuhlmueller** [comment]
Correct me if I'm wrong, but it seems that this issue isn't specific to webppl, and that there are [various ways](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server) to get node running on ubuntu.
