### ISSUE TITLE
MH and SMC throw error for models without erps

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#155]
Example:

    // Doesn't work:
    
    var x = MH(function(){
      return 1;
    }, 10);
    
    print(x);
    
    // Works:
    
    var y = MH(function(){
      return flip(.5);
    }, 10);
    
    print(y);

Error:

    Uncaught TypeError: Cannot read property 'score' of undefined
    MH.exit @ webppl.min.js:35

**Comment by null-a** [comment]
For reference this also affects `HashMH` and `IncrementalMH`. The existing `deterministic` test case triggers the bug.

**Comment by null-a** [comment]
#169 resolved this problem for `MH` and `SMC` and we no longer have `HashMH`.
