### ISSUE TITLE
SMC returns #particles * (#rejuvenation-steps + 1) samples

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#156]
`#samples = #particles * #rejuvenation-steps` would be more intuitive.

Example:

    var y = ParticleFilterRejuv(
      function(){
        return uniform(0, 1);
      }, 
      3, // particles
      5  // rejuvenation steps
    );
    
    y.support().length

This returns 18 = 3 * (5 + 1).

The explanation for the additional sample is that for each particle, we run SMC until we're at the end of the program, which gives us one sample per particle; then we additionally take #rejuvenation-steps MH samples, each of which gives us another sample.

**Comment by null-a** [comment]
Do you imagine achieving this by only returning the samples from the rejuvenation steps? (Taking `rejuvSteps - 1` steps seems like it would be more confusion than what we have now.)

**Comment by stuhlmueller** [comment]
Yes, if there's a way to do this and still have it return a sample in the case of 0 rejuvenation steps. If there is no elegant way, then the current solution of `#particles * (#rejuvenation-steps + 1)` samples isn't that bad either.

**Comment by null-a** [comment]
Closed by #169.
