### ISSUE TITLE
IncrementalMH with justSample option throws error

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#160]
As [reported](https://groups.google.com/forum/#!msg/webppl-dev/B0RNLrS_cws/4FQx2ZATBAAJ) by @mhtess.

It looks like this is caused by attempting to create an empty marginal ERP which now triggers an assertion failure. ([Relevant change](https://github.com/probmods/webppl/commit/b5253da0f4cff94b5be518d5e44d2476c057ba41).)

If we want to continue to not allow empty marginal ERPs we could perhaps make an ERP from the MAP estimate to be somewhat faithful to the inference interface. Thoughts?

We should also add inference tests for some of these options.

HashMH will also have this bug.

**Comment by dritchie** [comment]
Long term, I think this ought to be solved by:
 - Making inference routines return a set of samples (or 'the next sample')
 - Have separate processing/aggregation routines that describe what to do with the set of samples (or the next sample).

So you could express different queries as e.g. `MAP(IncrementalMH(...))` or `Marginal(IncrementalMH(...))`. I believe we've talked about this before.

**Comment by null-a** [comment]
> I believe we've talked about this before.

#86, in case anyone's interested.
