### ISSUE TITLE
Use linked list as primary data structure

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#174]
~~This would make copying trivially O(1).~~

~~See [ImmutableJS](https://facebook.github.io/immutable-js/).~~

~~This came up in #169.~~

**Comment by null-a** [comment]
I suspect header functions `map`/`reduce` and friends scale quadratically(?) in the length of the input array, presumably because of the `ar.slice(1)` at each step of the recursion. (This [example](https://github.com/null-a/webppl/blob/610914a2f3d7ceb952589895c3e323cb243f2ddc/examples/headers.wppl) shows something non-linear I think.)

Perhaps we need a persistent list data structure available in WebPPL?

(I think this might be a practical concern in BDA type models. For example it causes the data munging of a few thousand data points to take ~20 secs in the model [discussed here](https://groups.google.com/d/msg/webppl-dev/lEzC_1dAJY0/JyIbxFbvDQAJ).)

**Comment by stuhlmueller** [comment]
Yes, the scaling of `map` etc is quite bad.  On my computer, mapping `function(x){return x + 1;}` over a list of 6655 entries (all `1`s) takes 389ms, with 13310 entries it takes 1258ms, and with 26620 entries, the process runs out of memory:

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    Abort trap: 6

I'm not sure yet how we should resolve this problem globally (e.g., whether to replace the header functions with alternatives), but maybe we can start by creating a `webppl-immutable` package that provides a cons-like immutable list data structure and corresponding alternatives to `map` etc. This could solve the issue for concrete applications, and we'd be more informed when we think about what to do about core webppl.

**Comment by null-a** [comment]
> maybe we can start by creating a webppl-immutable package that provides a cons-like immutable list data structure and corresponding alternatives to map etc

I've started a [linked list implementation](https://github.com/null-a/webppl/commit/7a6227960e57907cfd164c84eff9fd6178e7e6cc).

On your test it gives the following:

 | Array (ms) | List (ms)
----|----|----
6655 | 258 | 23
13310 | 852 | 36
26620 | out of mem | 88

I've also tried it out on @mhtess's [model](https://groups.google.com/forum/#!msg/webppl-dev/lEzC_1dAJY0/JyIbxFbvDQAJ) and the results are promising:

 | Array | List
----|----|----
Memory use at 1st iteration (MB) | 1240 | 150
Run time (min:secs) | 1:54 | 0:26

I was able to double the size of the data set and still do inference (without seeing out of memory errors) something which neither @mhtess nor I can do with the array based implementation.

I ran into issues turning this into a package, I'll raise a separate issue for the underlying problem there.

**Comment by stuhlmueller** [comment]
Looks very promising!

**Comment by null-a** [comment]
> I ran into issues turning this into a package, I'll raise a separate issue for the underlying problem there.

The change mentioned in #202 fixes this problem, and we now have a [linked-list](https://github.com/null-a/webppl-linked-list) package.

I'll turn #202 into a PR if you think people might want to use this. If not, we can just sit on it until it bites us harder.

**Comment by longouyang** [comment]
Somewhat related problem: `repeat` scales poorly

**Comment by null-a** [comment]
> Somewhat related problem: repeat scales poorly

Very much related. To clarify for future readers, I think this poor scaling likely applies to nearly all of the functions in `header.wppl` which are defined recursively over arrays. e.g. `map`, `reduce`, `filter`, `repeat` etc.

The [linked list](https://github.com/null-a/webppl-linked-list) (WebPPL package) should have better scaling. It should work with the latest version of WebPPL from `dev`. 

There are no docs, but there's some example usage in the [tests](https://github.com/null-a/webppl-linked-list/blob/master/src/test.wppl). I'm happy to help anyone who wants to try it out.

**Comment by longouyang** [comment]
Would it be a bad idea to use linked lists by default, perhaps by transforming `[]` and associated functions into the linked list representation?

**Comment by null-a** [comment]
> Would it be a bad idea to use linked lists by default

It's the most obvious solution to my mind, though I suppose there are others. The [idea](https://github.com/probmods/webppl/issues/174#issuecomment-139610068) of the package was just to:

> solve the issue for concrete applications, and we'd be more informed when we think about what to do about core webppl.

**Comment by longouyang** [comment]
I think I've stumbled upon a useful improvement to the current array-based implementation

Instead of writing `map` like
```js
var map = function(fn, ar) {
  return ar.length === 0 ? [] : [fn(ar[0])].concat(map(fn, ar.slice(1)));
};
```

We can avoid repeatedly slicing via:

```js
var map = function(fn, inputAr) {
  var n = inputAr.length;

  var helper = function(outputAr, i) {
    if (i === n) {
      return outputAr
    } else {
      return helper(outputAr.concat([fn(inputAr[i])]), i+1)
    }
  }

  return helper([], 0)
}
```

I adapted Paul's code to measure `map` timing (rather than `filter`) and got the following numbers:

Timing:
![time](https://cloud.githubusercontent.com/assets/14802/12498040/7159b93e-c054-11e5-97ce-374c10f2f488.png)

Memory:
![memory](https://cloud.githubusercontent.com/assets/14802/12498045/7c9e2690-c054-11e5-9b7b-ccc945bfbe72.png)

**Comment by stuhlmueller** [comment]
Looks awesome! We should use this.

**Comment by longouyang** [comment]
Addendum: time complexity is still quadratic, as we're still calling `concat()` at every step:

![timing-100k](https://cloud.githubusercontent.com/assets/14802/12498258/099803c6-c056-11e5-9aec-b5ef33a17ae6.png)

So while we've clearly improved on the quadratic constant by removing `slice`, there is still room for improvement (which linked lists should achieve)

**Comment by longouyang** [comment]
Addendum 2: We can cut down the number of `concat`s to log n:

```js
var map = function(fn, inputAr) {
  var helper = function(l, u) {
    var n = u - l + 1;
    if (n == 0) {
      return []
    } else if (n == 1) {
      return [fn(inputAr[l])];
    } else {
      var n1 = Math.ceil(n/2);
      return helper(l, l + n1 - 1).concat(helper(l + n1, u));
    }

  }

  return helper(0, inputAr.length - 1)
}
```

Results:
![timing-log](https://cloud.githubusercontent.com/assets/14802/12500375/80d5f7b6-c067-11e5-91dc-2e868dce3d3d.png)

**Comment by null-a** [comment]
To check I understand this correctly, `map` now has O(n log n) run time/memory, right? (Assuming v8 doesn't do anything too fancy with `concat`, and that gc doesn't run.)

**Comment by longouyang** [comment]
Yes, I believe so.

**Comment by null-a** [comment]
I think we can make `map` linear (in time/space) with judicious use of mutation.

````js
var map2 = function(arr, f) {

  var iter = function(i) {

    if (i === arr.length) {
      return [];
    } else {
      var x = f(arr[i]);
      var rest = iter(i + 1);
      rest.push(x);
      return rest;
    }

  };

  // TODO: Lose the reverse.
  return iter(0).reverse();

};

Enumerate(function() {
  map2([0, 0.1, 0.9, 1], flip)
});

// ERP:
//     [false,false,true,true] : 0.8099999999999999
//     [false,true,true,true] : 0.08999999999999996
//     [false,false,false,true] : 0.08999999999999991
//     [false,true,false,true] : 0.009999999999999993


// var n = 1e6;

// console.time('map');
// map(idF, _.range(n));
// console.timeEnd('map');

// ~4400 ms

// console.time('map2');
// map2(_.range(n), idF);
// console.timeEnd('map2');

// ~1200 ms
````

One problem with this is that the depth of the recursion is now linear in the length of the input, so for really large arrays #150 becomes an issue I think. (I need to look at this more closely.) The current divide and conquer implementation isn't really affected by this as the depth of the recursion is logarithmic.

**Comment by longouyang** [comment]
1. I think we can avoid `reverse` by using `unshift` instead of `push`.
2. Can we combine divide and conquer with mutation?
3. I'm surprised that we can use mutation at all... when is mutation okay versus not?

**Comment by longouyang** [comment]
(nudge)

**Comment by null-a** [comment]
1. I expect this will end up been quadratic overall? (`unshift` is probably O(n) vs. O(1) `push`.)
2. What do you have in mind?
3. This isn't a complete answer to the mutation question, but the reason I think it's OK here is that it's local to a particular execution/possible world. So, in the implementation of `map` above it's important that the returned array is constructed *after* all the calls to `f`, as they may include random choices.

**Comment by longouyang** [comment]
1. Ah, that seems right.
2. I think I had in mind that we would recursively divide really large arrays into sub-arrays until they're small enough that #150 is not problem, then call your mutation map on each sub-array and recursively concat the results until we're done. But it sounds like that won't work if the returned array must be constructed after all the calls to `f`.
