### ISSUE TITLE
Rejuvenation for models with structural change

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#176]
See discussion in issue #20

**Comment by null-a** [comment]
I have [a version of rejuvenation](https://github.com/null-a/webppl/commit/911f03ea10e1399763fa11ab4b0d6cb53c7668d6) which seems to work on our `varFactors` tests. Here's a wordy attempt to explain what it does:

My understanding (loosely speaking) is that SMC is valid for any sequence of distributions which has the distribution of interest as a marginal, and not only for the typical state space model decomposition. The sequence of distributions we use in `ParticleFilter` seems a little odd from a state space perspective (as particles can be "out of sync") but it seems fine with respect to the criteria for valid SMC.

One might have a suspicion that something fishy could be happening when some particles finish before others. In such cases you can imagine padding the shorter paths through the program with additional `factor(0)` statements to ensure all particles encounter the same number of factor statements. I think of our implementation as doing this implicitly. Note that this suggests that particles which have reached the exit should be included in resampling, as indeed they are in `ParticleFilter`.

My understanding of the correctness of rejuvenation is that at each step of SMC, the rejuvenation kernel should have as its stationary distribution the distribution which the particles are approximating. With that in mind, all this change does is tweak the rejuvenation kernel for a given step `n` to have as its stationary distribution the distribution used by `ParticleFilter` at step `n`.

More specifically, assuming programs have been padded as mentioned, then `ParticleFilter` simply runs all particles to the first factor statement (the stack address of which may vary across particles) then resamples, then advances them all to the second factor statement etc., until all particles are done. So the distribution at step `n` is the distribution on traces you get by running particles up to the `n`<sup>th</sup> factor statement. To have this be the stationary distribution of the rejuvenation kernel, all we need to do is switch from truncating the program at the factor statement with a given stack address (as we do now), to truncating it at the `n`<sup>th</sup> factor statement encountered by the particle. That's what this change does.

So, the hope is that this version of rejuvenation will work wherever `ParticleFilter` works, and perhaps `ParticleFilter` works generally. (At present, I'm not very confident that this is the case.)

**Comment by stuhlmueller** [comment]
> In such cases you can imagine padding the shorter paths through the program with additional `factor(0)` statements to ensure all particles encounter the same number of factor statements.

That's a good way to think about it.

> To have this be the stationary distribution of the rejuvenation kernel, all we need to do is switch from truncating the program at the factor statement with a given stack address (as we do now), to truncating it at the `n`<sup>th</sup> factor statement encountered by the particle. 

Sounds like an improvement to me. I briefly checked with Noah to see whether there were reasons why we didn't take this approach in the first place, but it doesn't seem like there were good reasons. Create a pull request?
