### ISSUE TITLE
Introduction of the 'factor' notion in Chapter 2 

### ISSUE THREAD

**Issue by tomeru** [probmods/webppl#18]
I'm not sure what level of readership you're aiming at, but taking probmods.org as a benchmark, it feels like towards the end of Chapter 2 you're assuming a great deal of background knowledge for a casual reader. 

In particular, while the introduction of inference through the binomial function feels 'standard' and normal, this paragraph suddenly shows up after it:

"What if we wanted to adjust the above binomial computation to favor executions in which a or b was true? The factor keyword re-weights an execution by adding the given number to the log-probability of that execution. For instance:"

What 'given number' are we adding here? How much does a change of -2 correspond to? Why would we want to make that specific inference or assumption? In Church/probmods when inference was introduction the conditioning was on a pretty simple notion that 'the sum of the heads is 2 or greater'.

**Comment by stuhlmueller** [comment]
Agreed. [Moved this issue to dippl](/probmods/dippl/issues/16).
