### ISSUE TITLE
Caching transform is applied to wppl files in packages but not header.wppl

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#202]
This came up when I tried to extract my linked list code (#174) into a package. When the linked list code is in `header.wppl` it works great, but once I put it in a package I run into 'out of memory' issues. I've tracked down the cause of this difference to the fact that the caching transform is applied to `*.wppl` files loaded from packages, but not `header.wppl` in core WebPPL.

Would it make sense for package authors to have the option to opt-out of the transform so that package code can be equivalent to code added directly to `header.wppl`?

**Comment by stuhlmueller** [comment]
Yes, we could have a flag for this, and this may be a good short-term solution to this problem.

Longer-term, it is potentially worrisome that moving code between user-specified wppl and `header.wppl` results in such difference in performance for Incremental MH. What goes into the header is determined based on whether it will be useful across many programs. Now this decision is entangled with the decision what to cache, which may be correlated with the other criterion, but will likely come apart in some cases.

**Comment by null-a** [comment]
I have an implementation of this [here](https://github.com/null-a/webppl/commit/e377c5e1a3b795309cf49e379957ebd53f72649a).

> Longer-term, it is potentially worrisome that moving code between user-specified wppl and header.wppl results in such difference in performance for Incremental MH.

Indeed. My best guess as to what's happening would be that all of the intermediate results (of these recursive functions which operate on lists) are been cached. (I have low confidence in this guess however.) If that was the case, then perhaps a sufficiently smart caching strategy could notice this.

**Comment by stuhlmueller** [comment]
> I have an implementation of this [here](https://github.com/null-a/webppl/commit/e377c5e1a3b795309cf49e379957ebd53f72649a).

Nice, we should merge this.
