### ISSUE TITLE
Package wppl files concatenated in differing orders between browser/node

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#209]
This is problematic when there are dependencies between packages.

The current implementation for the browser is perhaps the most natural as packages are loaded in the order they are specified on the command line, and individual files within a package are loaded in the order they appear in `package.json`.

**Comment by stuhlmueller** [comment]
Yes, predictable load ordering is desirable, and making the command line act like the browser implementation is a natural short-term solution.

Longer-term, this should probably be more analogous to node packages in general, and offload as much of the work as possible to existing infrastructure. That is, for dependencies between packages, recursively require other packages via `package.json`. For files within a package, including wppl files, use explicit export/import.
