### ISSUE TITLE
Simplify arguments for inference tests

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#215]
I wonder if the test functions in `test-inference.js` should only take `test, result, expected, args` as arguments, with `hist` stored as part of `result`, or possibly not computed at all ahead of time, only in test functions that need it. Currently, the test functions look like this:

    var testFunctions = {
      hist: function(test, result, hist, expected, args) {
        test.ok(util.histsApproximatelyEqual(hist, expected, args.tol));
      },
      mean: function(test, result, hist, expected, args) {
        helpers.testWithinTolerance(test, util.expectation(hist), expected, args.tol, 'mean');
      },
      ....
    };

**Comment by null-a** [comment]
I computed it ahead of time to save having to do so multiple times per-test (I think every test uses it at least once), so I'll add it to `result`.
