### ISSUE TITLE
Pass source locations along transforms

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#22]
It would be useful to pass the source code locations along in the code transforms (CPS, addressing, optimizing, etc) in order to make debugging easier.

**Comment by stuhlmueller** [comment]
Pedram implemented this in the [stacktrace branch](https://github.com/probmods/webppl/tree/stacktrace), only needs to be merged.

**Comment by null-a** [comment]
I believe this is superseded by #292.
