### ISSUE TITLE
Split header into multiple files

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#23]
header.js is getting too long. it would be nice to split it up into several files (e.g. ERP, Enumeration, Helpers, etc). doing this naively using `require` doesn't work right, because the `coroutine` variable needs to be in scope for all these files. there is probably a good way to do this...

**Comment by stuhlmueller** [comment]
The same applies to the `_trampoline` variable.

Some options:

- Make the imported modules [parameterized](http://stackoverflow.com/a/7367898)
- Add utility functions for getting/setting `global.coroutine` (or `window.coroutine` in browser)

**Comment by stuhlmueller** [comment]
I started working on this in branch [header-split](/probmods/webppl/tree/header-split) (based on the first option I proposed above).

**Comment by stuhlmueller** [comment]
Done.
