### ISSUE TITLE
Remove hard-coded drift kernel parameters

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#231]
The [variance](https://github.com/probmods/webppl/blob/5c1212762cfa0184d39b652f4f8452451c20628c/src/erp.js#L618) and [concentration](https://github.com/probmods/webppl/blob/5c1212762cfa0184d39b652f4f8452451c20628c/src/erp.js#L623) parameters of drift kernels are currently hard-coded. Presumably it should be possible to specify these from within a program or perhaps have them tuned automatically.

**Comment by longouyang** [comment]
(Summarizing our slack chat here)

With the new ERP interface, the kernels can take drift parameters by accessing `this.params`, e.g., for `dirichletDrift`:

```js
var dirichletDrift = makeErpType({
  name: 'dirichletDrift',
  parent: dirichlet,
  driftKernel: function(prevVal) {
    var concentration = this.params.driftConcentration || 10;
    var alpha = prevVal.map(function(x) { return concentration * x; });
    return new dirichlet({alpha: alpha});
  }
});
```
