### ISSUE TITLE
Scores of constructed ERP's

### ISSUE THREAD

**Issue by mattbarr** [probmods/webppl#24]
For ERPs constructed from marginalization functions (EnumerateLikelyFirst, for example), while the 'support' method of the object returned by the marginalization function returns the appropriate set, it seems that all of the 'score' return values are '-Infinity'. 

Is it expected that the 'score' should simple return the negative log of the values displayed in the "Creating distribution:" output?

More concretely, should the following expression return the negative log probability of the first element?
<code>
var inference = EnumerateLikelyFirst(function,num_queue)
console.log(inference.score(inference.support()[0]))
</code>

My current attempts to do so return the proper support, but return "-Infinity" for the score, even though inference does not lead to a zero result.

**Comment by ngoodman** [comment]
score functions take an array of erp params first, so try:
var inference = EnumerateLikelyFirst(function,num_queue)
console.log(inference.score([],inference.support()[0]))


-N
