### ISSUE TITLE
ESLisp + Webppl

### ISSUE THREAD

**Issue by wuxianliang** [probmods/webppl#260]
Dear friends:
I suggest a eslisp ( by @anko ) module for webppl which we can code in lisp ( s-expression/macros ) and execute in javascript seamlessly. ESLisp is still immature, and both eslisp and webppl are not support ES6, so that is a good time for considering other opportunity. 
It is great to code in lisp with javascript ecosystem for probabilistic programming seamlessly one day.

https://github.com/anko/eslisp

**Comment by stuhlmueller** [comment]
Thanks for the proposal! We'd be happy to see someone to implement such a module, but won't have core developer capacity for this in the foreseeable future. However, we might be able to provide a compiler from [webchurch](https://github.com/probmods/webchurch) at some point.
