### ISSUE TITLE
Don't cps transform calls to external require() functions

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#261]
The [md5 package from node](https://www.npmjs.com/package/md5) provides a function as its export rather than an object mapping keys to functions, i.e., running `require('md5')` in vanilla node returns a single function rather than an object with functions as properties.

I'd like to use this package but encountered an issue; it appears that webppl tries to run `md5` as a cps-transformed function.

As a minimal example, I tried running the following webppl program:

```js
md5('abcdefg')
```

in the usual way (`webppl foo.wppl --require md5`) but got this error:

```
Processing foo.wppl
undefined:5
            trampoline = trampoline();
                         ^

TypeError: trampoline is not a function
    at eval (eval at <anonymous> (/Users/long/webppl/src/main.js:171:10), <anonymous>:5:26)
    at /Users/long/webppl/src/main.js:171:36
    at Object.timeif (/Users/long/webppl/src/util.js:224:37)
    at Object.run (/Users/long/webppl/src/main.js:170:8)
    at run (/Users/long/webppl/webppl:27:10)
    at main (/Users/long/webppl/webppl:120:3)
    at Object.<anonymous> (/Users/long/webppl/webppl:123:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

I've put a comment on the culprit in the compiled js:

```js
var main = (function (p) {
  return function (s, k, a) {
    var trampoline = p(s, k, a);
    while (trampoline) {
      trampoline = trampoline();
    }
  };
}(function (globalStore, _k0, _address0) {
  return function () {
    return md5(globalStore, _k0, _address0.concat('_123'), 'abcdefg'); // shouldn't do this
  };
}));
```

I'm currently using the following workaround but I'm wondering if there's a more principled workaround we can build into webppl:

```js
globalStore["md5"] = md5;
globalStore.md5('abcdefg')
```

**Comment by stuhlmueller** [comment]
You could use `md5.call(null, "abcdefg")`.

**Comment by longouyang** [comment]
This is essentially a duplicate of #211, so I'll close
