### ISSUE TITLE
Expand primitive ERPs for Bayesian data analysis

### ISSUE THREAD

**Issue by mhtess** [probmods/webppl#263]
[Here, Gelman recommends](http://www.stat.columbia.edu/~gelman/research/published/taumain.pdf) using a [Cauchy prior](https://en.wikipedia.org/wiki/Cauchy_distribution) (in addition to Uniform and half-Normal) for variance in hierarchical models. There are also expanded discussions in the article about parametrization that improves MCMC convergence (see Section 3.2). Some or all of this wisdom could be useful for BDA. Minimally, we should have a primitive Cauchy ERP.

**Comment by null-a** [comment]
Closing since we now have a Cauchy ERP. I think we should open new tickets for any further changes.
