### ISSUE TITLE
Make all arguments to ERPs named parameters

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#268]
How would people feel about replacing calls such as `gaussian(0, 1)` and `cauchy(2, 1.5)` with `gaussian({mean: 0, std: 1})` and `cauchy({location: 2, scale: 1.5})`?

**Comment by stuhlmueller** [comment]
This is really two proposals in one. First, one could change how the wrapper functions in `header.wppl` work (as illustrated above). Second, one could change the ERP interface itself, e.g. turning `sample(gaussianERP, [0, 1])` into `sample(gaussianERP, {mean: 0, std: 1})`. We don't necessarily have to do both of these.

**Comment by ngoodman** [comment]
i think this is a great idea -- it'd hard to keep track of the params as arrays. it seems most reasonable to change the ERP interface, and then to have the wrapper functions work both ways if possible (because sometimes you just want to write `flip(0.5)` or `gaussian(0,1)`....).

**Comment by ngoodman** [comment]
Note this is related to #246.

**Comment by null-a** [comment]
Closed by #393.
