### ISSUE TITLE
Update sweet.js

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#270]
The way I made browserify work with macros (#153) is rather ugly. In particular I had to:

1. [Patch](https://github.com/probmods/sweet.js/commit/77d2efdb8f4d81a6b57b8891bc3b1fa6e14c1d9e) sweet.js.
2. Pin us to an old version of brfs. (I mention one of the reasons for this [here](https://github.com/substack/static-module/issues/17).)
3. [Switch](https://github.com/probmods/webppl/blob/1258853f49c8ae2b97b283e816afcfba382e7ce5/compiled/Makefile#L16) to applying brfs globally. (`browserify -g` rather than `-t`.)

We'll presumably need to re-visit this at some point.

**Comment by null-a** [comment]
The sweet.js people have been working on a redesign, and it's now at pre-release stage. It looks like this will become their v1. Once it's done, I should take a look as it might open up new possibilities for fixing this issue.

**Comment by null-a** [comment]
The new version of sweet.js is available. It's missing a few features from the old version we rely on, so we'll need to wait until some of those are reinstated before we can switch. (e.g. See their issues 513, 514, 517.)

**Comment by null-a** [comment]
I took another look at this to try to better understand what would be involved in upgrading to the current version of sweet.js. Here are some things we need to consider:

- sweet.js has lost the ability to define custom infix operator, though this may be temporary. (See their issue 517.) We currently use this feature for AD, but it seems like it would be pretty straight-forward to write an extra transform to do the same thing. (Either directly rewrite to equivalant adnn, or transform infix operators to functions and use macros to transform those. IIRC the latter was @stuhlmueller's idea.) Do custom operators get used anywhere else in webppl land?
- sweet.js no longer uses the same AST format as we do, so assuming we don't want to rewrite all of our code transforms I think we'll need to covert the thing we get back from `sweet.parse` into the correct format. (Perhap using [this](https://github.com/shapesecurity/shift-spidermonkey-converter-js), or, if we're really stuck, we could code gen and then parse the result using esprima.)
- sweet.js has lost its readable names option -- again this may be temporary. (See their issue 514.) Without this, sweet.js renames all identifiers during macro expansion, which prevents us from using the current strategy of parsing the header, user code, and package code separately. (IIRC one reason we do this is so that macros from one package aren't applied to code from some other package.) If we address that, there's also the question of whether this variable renaming would leak through to run-time error messages -- I'm not entirely sure about that.
- You now specify which sweet.js modules to load by using ES6 style inline `import` statements rather than by passing them as an argument to `sweet.parse`. The package system will need updating to reflect this, though it may be as simple as prepending appropriate `import` statements to webppl code before parsing.
- Browser support. It's possible that the new version of sweet.js only supports the very latest browsers. For example, I tried using their web editor with Safari 9 and it didn't work, but upgrading to (the very new) Safari 10 got things working. We should clarify what browsers are supported before we upgrade.

**Comment by stuhlmueller** [comment]
What do you think we should do? Get rid of macros/sweet.js so that we can get the performance benefits you documented in #484, or wait until the new sweet.js version gains some or all of the missing features and upgrade then?

**Comment by null-a** [comment]
I'm not sure, but if no one is using or plans to use macros (I'm still working on figuring out if this is so), and #484 is a thing that hurts us, then I think we should probably drop it. (Or at least give it a go and discover all the things I've not considered...)

In part, this is because removing it now and then adding it back in later doesn't seem like much more work than the upgrade would be. In the mean time, #484 stops hurting and there's a chance someone will get time to make progress on some of the ES6 related things this currently blocks.

I guess the worse thing that could happen in removing macros would be to realize we'd made a mistake and that we need them back, and even that doesn't seem *too* bad.

A few things to consider if we do remove macros:

* By using sweet.js our syntax errors improved. (See [here](https://github.com/probmods/webppl/issues/124#issuecomment-169516213).) However, I briefly played with the demo on the esprima web site and it seemed like the syntax errors it gives are pretty similar to the ones we get from sweet.js? It's probably worth me taking a closer look to make sure we understand this.
* I think webppl-editor tries to parse the location of a syntax error from the text of the exception. If we remove/upgrade sweet.js then this will need updating accordingly.
* Probably not a big deal, but I wondered if we might address #2 with macros.

**Comment by null-a** [comment]
> I'm not sure, but if no one is using or plans to use macros (I'm still working on figuring out if this is so)

A week has passed since I [posted a message to the mailing list](https://groups.google.com/d/msg/webppl-dev/Ll3PcRqj95Y/kKGmrIWsAQAJ) asking whether anyone uses macros, and so far no one has replied to say they do. @dritchie mentioned he might be able to make use of macros in an upcoming project, but he doesn't think it's worth keeping them around for that alone.

So it looks like the option of removing macros is open to us. The next step is probably for me to start an experimental branch to check this is feasible.
