### ISSUE TITLE
Use the Histogram prototype in all inference algorithms

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#284]
[`Histogram`](https://github.com/probmods/webppl/blob/875812b2eb538098b248b5eec214925465c70301/src/aggregation.js#L6) is only used in `MCMC` and `SMC` but could be used for other inference algorithms.

Using it in sampling algorithms will be straight-forward I think. A little work will be needed to get it working in `Enumerate` since:

*  At present all values added to `Histogram`are given equal weight.
* `Enumerate` does some [extra work](https://github.com/probmods/webppl/blob/5988c5e0a39ee4666953f6ed1407e01f4e30a408/src/inference/enumerate.js#L128) to avoid underflow. (History: #109.)

**Comment by null-a** [comment]
`IncrementalMH` and `MCMC` differ in their handling of the `onlyMAP` and `justSample` options. It seems sensible to remove these differences as part of switching `IncrementalMH` over to using `Histogram`. I'm not sure how to best to resolve the differences, so for now I'll just describe them. If you have an opinion about how to proceed, let me know.

**`justSample`**

In `MCMC`, `marginal.samples` is an array of program return values, whereas in `IncrementalMH` it is an array of `{value: ..., score: ...}` objects.

**`onlyMAP`**

`IncrementalMH` returns a MAP estimate (the return value of the program execution with the highest score) as `marginal.MAP`. This happens regardless of the setting of `onlyMAP` and `justSample`. If either `onlyMAP` or `justSample` are `true`, then the full marginal is replaced by a delta ERP with its mass on the MAP estimate.

`MCMC` on the other hand never sets `marginal.MAP`. (In part, because doing so masks the `ERP.prototype.MAP` function, though that doesn't compute the same thing. #140.) Instead, the MAP estimate is only returned when `onlyMAP` or `justSample` are `true`, and only as part of a delta ERP on the MAP estimate.

**Comment by stuhlmueller** [comment]
I don't have strong opinions either, but here's my quick impression:

- `justSample` and `onlyMAP` should be mutually exclusive.
- `justSample` should return `{value: ..., score: ...}` objects. This allows users to find the highest-scoring sample(s) if they're interested after all.
- `onlyMAP` should return a delta ERP with its mass on the highest-scoring execution. `marginal.MAP` should remain unaffected, and should refer to the `MAP` of the marginal as opposed to the MAP of the joint distribution.

(I wonder if it would be more elegant to merge the two options so that users can specify some number `k` of highest-scoring samples to be returned, with `onlyMAP` corresponding to `k=1` and `justSample` corresponding to `k=infinity`.)

**Comment by null-a** [comment]
I think I'd like to try to minimize the impact of any changes on the interface caused by tackling this issue. I completely agree that it's very likely we can clean-up what we have at present, but I'd like to pass on that for now as I think it needs more thought. Instead, we can tackle it as part of #86/#140.

Following your suggestions, I think the simplest way of using `aggregators.js` everywhere would involve the following changes:

* MCMC would return `marginal.samples` as an array of `{value: ..., score: ...}` objects rather than an array of sampled values when `justSample=true`. The mirrors the current behavior of `IncrementalMH`.
* IncrementalMH would no longer modify `marginal.MAP`. Instead the only way to get at its MAP estimate (highest scoring execution) would be via the delta ERP, which would be used when either `onlyMAP=true` or `justSample=true`. This mirrors the current behavior of `MCMC`. It also means that `marginal.MAP` would have the same meaning across all algorithms, i.e. MAP of the marginal.

How does that sound?

**Comment by stuhlmueller** [comment]
Sounds good.
