### ISSUE TITLE
MH proposals from distribution with custom params

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#29]
Drift propsals (i.e. proposals that are close to the current value) are often much more efficient for MH. A fairly general way to do this is to propose from the ERP being used but with different parameters that make the mean (close to) the current value. 

So we can add a general interface that takes a computedParams(curVal, params) and returns some appropriate new params. For instance for gaussian it could use the curVal as mean:
    function computedParams(curVal, params) {return [curVal, params[1]]}

Need to add appropriate forward/backward scores for these proposals to the MH ratio.

**Comment by stuhlmueller** [comment]
Pedram has a version of this in a local branch; needs to be cleaned up and merged.
