### ISSUE TITLE
Support drift proposals for more ERPs and document how to use them

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#308]
Also, support fine-tuning of drift parameters (#231).

**Comment by stuhlmueller** [comment]
Also, add tests. We should have noticed the wonky concentration parameter for the Dirichlet drift ERP (#309).

**Comment by null-a** [comment]
>  We should have noticed the wonky concentration parameter for the Dirichlet drift ERP 

Please could someone explain what the idea is behind the dirichlet drift kernel? Proposing from a dirichlet with params `alpha * 10` seems it *might* be a useful thing to do if the prior is something like a symmetric dirichlet with `alpha=0.1`, but if the prior has parameters `alpha=1` then aren't we proposing from a dirichlet with its mode in the middle of the simplex? The thing I'm most surprised by is the fact that the value of the previous sample is not used at all, wouldn't it be useful to propose from a dirichlet with it's mode at the value of the previous sample as we do with the gaussian?

**Comment by stuhlmueller** [comment]
> The thing I'm most surprised by is the fact that the value of the previous sample is not used at all, wouldn't it be useful to propose from a dirichlet with it's mode at the value of the previous sample as we do with the gaussian?

Wait, that's not what we are doing? You're right, of course, `params` in `dirichletProposalParams` should be `prevVal`.

**Comment by ngoodman** [comment]
Btw in general if a Dist is parameterized by mean (and other params) we want the drift proposal to be sampled from the same family but mean equal to the current value of the choice (and other params set based on a proposal width parameter). For Dists that don't naturally have mean as a param, we may want to use a different Dist for proposals (eg for Uniform we'd probably want a scaled Beta).

**Comment by ngoodman** [comment]
Also, we may want to unify the way we declare drift proposals and importance distributions, which are really very very similar.

**Comment by null-a** [comment]
> we may want to unify the way we declare drift proposals and importance distributions

In my mind, I've been imagining we'll tackle this after the guide stuff/VI is merged. BTW, there's issue #119 for this.

**Comment by longouyang** [comment]
FYI, the uniform drift I implemented in #418 uses a uniform proposal; we should switch this to scaled Beta as Noah suggests. (this might also help with the test failures reported in #430)
