### ISSUE TITLE
Make 'arguments' work in all contexts

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#31]
Currently, the varargs transform happens before trampolining (so closures introduced there are handled correctly), but after cps (so if cps introduces a closure boundary that separates the occurrence of `arguments` from its corresponding function top level, `arguments` won't work correctly). See example in e22b7e25d5f654f785eed124b4923b53bae4e00f.

**Comment by dritchie** [comment]
I've run into trouble with this as well. I tried the obvious thing of moving the varargs transform before the cps transform, but this causes all the tests to fail with 'maximum call stack size exceeded.' I haven't dug into why. I'm just using a workaround for now.

**Comment by stuhlmueller** [comment]
In case others are wondering about this, the workaround of having the first statement in a function be something like `var myargs = arguments` (and then only using `myargs` later) has always done the trick for me so far.

**Comment by dritchie** [comment]
On a related note: is there any workaround for getting `apply` to work correctly? Since it's invoked as `fn.apply`, it seems that it's being recognized as a method invocation, and thus treated as a primitive function where the (store, continuation, address) triplet isn't passed in.

**Comment by dritchie** [comment]
nvm, I just found it in `header.js`.
