### ISSUE TITLE
Document globalStore

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#310]

**Comment by null-a** [comment]
Documenting `query` is now #402.

**Comment by null-a** [comment]
Here's my attempt at some [global store docs](https://gist.github.com/null-a/4faef745d8403d2add8d1a66c14bb61d). Is this anywhere close to what you had in mind?

**Comment by dritchie** [comment]
These are quite nice, IMO :)
One thing: I believe that attempting assignment in WebPPL generates a compile-time error, not a runtime error.

**Comment by null-a** [comment]
> I believe that attempting assignment in WebPPL generates a compile-time error, not a runtime error.

Ah, yes, thanks!

**Comment by ngoodman** [comment]
this is great, thanks!
