### ISSUE TITLE
When webppl is loaded in the browser, console.log its version

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#313]
Log the git tag (which corresponds to the npm version) if we're at a tag, otherwise the git commit hash.

**Comment by stuhlmueller** [comment]
It would be useful to have this for each package as well.

**Comment by null-a** [comment]
The way this is implemented at the moment [doesn't work](https://github.com/probmods/webppl/pull/341#issuecomment-185926219) with everyone's git workflow. The fix is to pull the version from `package.json` instead. This could also work for #342.
