### ISSUE TITLE
IncrementalMH behavior when sampled from ERP depends on random choices

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#316]
I noticed that in the following model, the marginal given by `IncrementalMH` differs from those given by other algorithms.

````js
var mostlyTails = bernoulliERP.withParameters([0.2]);
var mostlyHeads = bernoulliERP.withParameters([0.8]);

var model = function() {
  var x = flip();
  sample(x ? mostlyHeads : mostlyTails, []);
};

//Enumerate(model);
// ERP:
//     false : 0.5
//     true : 0.5

//MCMC(model, { samples: 10000 });
// ERP:
//     false : 0.5045000000000001
//     true : 0.4955


IncrementalMH(model, 10000);
// ERP:
//     false : 0.7888788878887889
//     true : 0.2111211121112111
// ERP:
//     true : 0.788978897889789
//     false : 0.211021102110211
````

As a guess, the ERP which is passed to `sample` on the first execution is used for all executions. Is this a bug, or am I missing something?

I came up with this while trying to understand why I couldn't get my nested Enumeration tests (#293) passing for `IncrementalMH`. I think this is why.

**Comment by dritchie** [comment]
I'll dig into this in a little bit when I get some time. I seem to 
recall having some problems with IncrementalMH not playing well with 
direct calls to 'sample' before, but I thought I'd resolved that issue. 
We'll see.
