### ISSUE TITLE
Clean-up header.wppl

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#323]
Andreas said:

>  I think there are too many functional programming utils in the header. we should keep the important ones and move the rest to a package

**Comment by null-a** [comment]
We should also consider splitting `header.wppl` into a number of smaller files, as suggested in #353.

**Comment by null-a** [comment]
To help me understand which header functions we can move out to a package I've [counted](https://gist.github.com/null-a/7890b9640c5e3736f0d438525e172141) how often each function is used across the webppl examples, inference tests, forest and agent models.

I intend to share a list of which functions I suggest we move out in the next week or so.

In the meantime, please let me know if there is any more webppl code floating around that I can use in this analysis. Thanks.

**Comment by null-a** [comment]
As promised, here's the list of functions I suggest we move out of the header:

```
plus
minus
mult
div
and
or
eq
neq
lt
gt
leq
geq
isEven
isOdd
cons
snoc
rest
mapN
ringForward
ringBackward
mapPairs2
mapPairsC
mapPairsNC
mapReduce
mapReduce1
insertAt
removeAt
replaceAt
drop
take
dropWhile
takeWhile
span
push
everyOther
sortOn
```

I'm planning to add all of these to a package except for the functional versions of the binary operators (`plus`, `minus` etc.) as it sounds like these only exist because they are left over from a time when webppl didn't support binary ops. I'll probably do this in a few days time.

None of these were used in the code I looked at, details [here](https://gist.githubusercontent.com/null-a/9c62722e320ba8fe1f74fad088648dd5/raw/2458f9a54a3cc94b58552944bf1ea1b3aeb68dff/header-fn-analysis.txt).

**Comment by ngoodman** [comment]
the only of these that i can imagine using (e.g. in probmods) are `rest`, `take`, and `drop`. we should keep `rest` for historical reasons. maybe there are more idiomatic ways to do `take`/`drop` anyhow?

otherwise sounds good!

**Comment by null-a** [comment]
Great, thanks! Will make sure to hang on to `rest`.

> maybe there are more idiomatic ways to do take/drop anyhow?

`rest(arr)`, `drop(..., arr)` and `take(..., arr)` are just thin wrappers around `arr.slice(...)`, which I suppose is the idiomatic JS thing.

**Comment by null-a** [comment]
Before I start on this, it's probably worth having a quick think about what we're going to call the package that these functions will end up in.

An obvious suggestion would be something like "functional utils", but that doesn't seem very informative when the whole language is supposed to be functional. For the most part, these are (higher-order) functions that operate on arrays, so perhaps something like "webppl-array-utils"?

A more specific name like this might help to prevent the package from turning into a dumping ground, which seems desirable. On the other hand, if we *want* such a thing (I don't think so) maybe it should be called something like "webppl-header-extra".

Thoughts?

**Comment by stuhlmueller** [comment]
`webppl-array-utils` sounds good to me. Of the functions you listed above, the non-array-related ones don't look very useful, so I think we can just get rid of them.

**Comment by null-a** [comment]
The new package is at [webppl-array-utils](https://github.com/probmods/webppl-array-utils).
