### ISSUE TITLE
Document header functions

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#324]
We should probably do #323 first.

**Comment by null-a** [comment]
@hawkrobe added some [annotations to the header](https://github.com/probmods/webppl/commit/03ae8889546f2383f3636f8c769605e7c8afcf44).

**Comment by null-a** [comment]
The work @hawkrobe [started on this](https://github.com/probmods/webppl/commit/03ae8889546f2383f3636f8c769605e7c8afcf44) describes header functions by comparison to similar functions in `underscore`. This approach is a little surprising to me, but that might just be because I have a different perspective on webppl over here. (I suppose if I *did* compare header functions to something else in the docs, I'd be more likely to choose their JS counterparts.) 

So, before I start working on this myself I just want to check: do you want me continue in this vein, describing functions where possible by their differences to `underscore` versions?

**Comment by stuhlmueller** [comment]
I'd describe the functions without comparison to anything, and maybe name the JS counterpart where appropriate.

**Comment by ngoodman** [comment]
I'm going to call this done, since additions or refinements can happen organically now.
