### ISSUE TITLE
Document time/space complexity of inference algorithms

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#325]

**Comment by ngoodman** [comment]
It's worth thinking carefully about how meaningful space/time numbers are, given that statistical efficiency is the gold standard. That said, it would be useful to add some comments about the intuitive tradeoffs and scalings to the inference method documentation.

**Comment by stuhlmueller** [comment]
It would also be helpful if the documentation showed for each algorithm a short model where this algorithm is particularly well-suited compared to the other algorithms supported by webppl.

**Comment by longouyang** [comment]
I think just having coarse grained information would be useful.

e.g., if I have a model with 1000 rvs, it'd be useful to know that I should avoid a certain algorithm because, say, it's runtime is cubic in the number of rv's or something.

**Comment by null-a** [comment]
This probably depends on #329.

**Comment by ngoodman** [comment]
i think this will actually be harder than it sounds. i'm going to move it later in the milestones, so that it doesn't slow down other progress.

**Comment by stuhlmueller** [comment]
This probably doesn't need to be part of core webppl work, but will instead happen as part of the PPAML course preparation.
