### ISSUE TITLE
Review installation/basic usage docs, check they are clear

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#326]

**Comment by erindb** [comment]
Is this talking about [docs.webppl.org](http://docs.webppl.org/)?

**Comment by null-a** [comment]
Yes, I think so. I guess the 'Quick start' and 'Usage' pages?

**Comment by erindb** [comment]
OK. In the 'Usage' page, this is kind of a rabbit hole for me:

> To use webppl in web pages, include the browser bundle:
> 
> `<script src="webppl.js"></script>`
> `<script>webppl.run(...)</script>`

It's not obvious to me how to interpret the information in the [browser bundle](http://docs.webppl.org/en/master/development/workflow.html#browser-version) link if I'm a user of webppl and I've installed it globally with npm.

**Comment by erindb** [comment]
I wonder if it might be nice to provide a compiled `webppl.js` download somewhere and link to that on the usage page?

**Comment by chrisranderson** [comment]
Thoughts on this:

#### quick start
- Would a sentence or two about node/npm would be helpful? I expect most folks reading this aren't very familiar. I've found installing node painful in the past - a link to instructions could be better than a link to the homepage.
- A small sample program could be nice to make sure things are working. Is there a page that runs you through your first webppl program?

#### usage
- maybe running things in the browser deserves its own page, linked to from usage or quick start. Then maybe merge usage and quick start. Wouldn't browser usage be rare?
- random seeds seems out of place for a getting-started type page. Could that be placed in the debugging page?

**Comment by chrisranderson** [comment]
Quick start was changed in #559.

**Comment by null-a** [comment]
> random seeds seems out of place for a getting-started type page. Could that be placed in the debugging page?

Your new quick start page seems to cover the "getting-started" case.

The "usage" page seems to me to be mostly a reference for the options available when running webppl on the command line. 

Including `--random-seed` in this seems ok. It's already mentioned in the `Development -> Testing` section.

If this section *is* about command line usage, then perhaps we should also mention the `--require` option and link to the "Packages" page?

> Wouldn't browser usage be rare?

I would expect so. Moving those browser bits into `Development -> Workflow -> Browser version` might not be ideal, but it seems like an improvement. @longouyang may have thoughts about this?

Something that crossed my mind looking at this is that we don't mention the fact that you can use webppl online at webppl.org anywhere. Maybe we should, just in case someone manages to miss that fact but still end up at the docs? Maybe we present two options under "Quick Start", in browser at webppl.org and a local installation using Node?

**Comment by longouyang** [comment]
Moving browser bits into `Development -> Workflow -> Browser version` for now sounds fine.

+1 to mentioning online editor at webppl.org

**Comment by chrisranderson** [comment]
I'll submit a PR with the online editor mention, `--require` in Usage, and the browser stuff moved.
