### ISSUE TITLE
Establish best practices for large datasets and large models

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#329]
~~i.e. Scaling w.r.t. number of variables and size of data.~~

This came up in the context of providing a solution for inference in larger datasets.

**Comment by ngoodman** [comment]
It's unclear what the actual todo is for this issue. Does anyone have something specific in mind? If not maybe it should be removed from this milestone....

**Comment by null-a** [comment]
Noah said:

> Before embarking on this we should identify a couple of target models for evaluation. Probably some of MHs BDA models would do....

**Comment by stuhlmueller** [comment]
I'll try to deal with this as part of preparing the Algorithms chapter of the PPAML course.

**Comment by stuhlmueller** [comment]
I assume this will be dealt with as part of the [Data - analysis and prediction](http://probmods.github.io/ppaml2016/chapters/5-data.html) chapter, so will close it. If someone has specific TODOs in mind that fall under this topic, feel free to reopen or create a new issue.
