### ISSUE TITLE
Basic I/O

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#336]
We'll need a simple way to do basic I/O for the summer school. There are lots of ideas in #146 but it's not clear which of those we need here, or if there's anything else that's likely to be useful.

(I originally wondered whether we'd need anything like this in the browser, but Andreas thinks not.)

**Comment by ngoodman** [comment]
I don't think we need anything beyond what's already been implemented in csv, json, and fs packages. We will need docs, but that's part of #328.
