### ISSUE TITLE
Update dippl to reflect new interfaces; integrate new editor + viz

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#352]
Once #86, #246, #268 are done.

**Comment by stuhlmueller** [comment]
This depends on `webppl-viz` being compatible with the new distribution interface ([issue](https://github.com/probmods/webppl-viz/issues/26)).

**Comment by stuhlmueller** [comment]
I've started porting this over. I'll use this issue to keep track of dependencies that come up:

- [ ] [Integrate new code boxes with literate webppl/markdown editor](https://github.com/probmods/webppl-editor/issues/22)

    We don't want people's (localStorage) files on webppl.org (and also dippl.org/editor) to become inaccessible when we switch to new code boxes.

- [ ] [Handle "// language: javascript" for setting code box language](https://github.com/probmods/webppl-editor/issues/21)

    Javascript code is used all over the place in dippl.

- [ ] Merge [error handling](https://github.com/probmods/webppl/pull/425)
