### ISSUE TITLE
Make distributions easier to find in source

### ISSUE THREAD

**Issue by jsalvatier** [probmods/webppl#353]
Since there's no documentation for the distributions/functions, its probably good to have very descriptive names for the files so that users can easily look up what distributions there are and what their arguments are. Similarly for functions. Currently they're in `header.wppl`, which I never remember even though I've looked it up before.

I would split `header.wppl` into two files: `distributions.wppl`/`erp.wppl` and `functions.wppl`

**Comment by null-a** [comment]
Good idea. I think we should consider splitting up `header.wppl` as part of #323.

Adding documentation for ERPs (#87) and the header (#324) are included in the next two milestones.
