### ISSUE TITLE
require calls in models don't work on the command line

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#379]
As we discovered in #370, we lost the ability to write `require.call(null, 'library')` after commit 3744dc7

Some possible solutions:

1. When we're on the command line, run `eval(code)` instead of `eval.call(global, code)` inside the main.js `run` function. I'm not sure if this undoes the integration of `webpplEval` and `run`, though.
2. Write a header.js function, `jsRequire`, which calls `require` for us. This has the advantage that we can get rid of the `.call` syntax in models:

```
/// inside header.js
 env.jsRequire = function(s,k,a,dependency) {
    var lib = require(dependency);
    k(s,lib);
 }

// inside a model
var fs = jsRequire('fs') // just works
```

**Comment by null-a** [comment]
I believe this is a duplicate of #211?

**Comment by longouyang** [comment]
Oh, right. I'll propose my second option as a stopgap measure on that thread then
