### ISSUE TITLE
Enable debugger; statements in webppl code

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#38]
Pass through `debugger;` statements to compiled code. This requires that cps deals with nodes of type `DebuggerStatement`.

**Comment by null-a** [comment]
This is a little tricky. It looks like the cps transform turns *everything* into an expression making it difficult to include statements such as `debugger`.

One way to make this work is to side-step the problem by wrapping `debugger` statements in a function. After compilation, a `debugger` statement then becomes something like:

```
var _dummy1 = (function (globalStore) { debugger; })(globalStore);
```

This isn't ideal, but it works. (Code [here](https://github.com/probmods/webppl/compare/dev...null-a:debugger).)

I can think of 2 alternatives/improvements:

1. Figure out how to include statements in cps directly. It's not clear to me what this would involve.
2. Have a post-processing step which takes the current output and removes the redundant assignment and wrapper function.

**Comment by stuhlmueller** [comment]
> One way to make this work is to side-step the problem by wrapping debugger statements in a function. 

What are the drawbacks of this approach? A single extra function call on the stack? Does this lead to some environments becoming inaccessible from the debugger, or is it just an extra click?

**Comment by null-a** [comment]
I think user unfriendlyness was my concern, but you're right it's just  
an extra call on the stack and an extra click.
