### ISSUE TITLE
Go through codeclimate issues, fix where sensible

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#39]
https://codeclimate.com/github/probmods/webppl/code

**Comment by stuhlmueller** [comment]
Other issues that will help make the code more readable: #23, #32

**Comment by stuhlmueller** [comment]
To fix this issue...

> The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.

...use

    _.each(jsObject, function(val, key) {
      ...
    });

...instead of...

    for (var key in jsObject) {
      if (jsObject.hasOwnProperty(key)) {
        ...
      }
    }

**Comment by pedir** [comment]
As a first step in cleaning up the code, created a new lint branch which sets up Grunt to run Google Closure Linter and JSHint on the code. It can also automatically fix basic lint errors by running "grunt fixstyle".
