### ISSUE TITLE
Replace "ERP" terminology with "distribution"

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#400]
Based on the discussion in #393, let's call the distribution objects just "distributions" (shortened to `dist` for use in places where we currently use `erp`; the base class `ERP` would become `Distribution`). We should also use capital letters to indicate distribution types (`gaussianERP` -> `Gaussian`).

**Comment by null-a** [comment]
As part of this we should probably rename [`aggregation/distribution.ad.js`](https://github.com/probmods/webppl/blob/dev/src/aggregation/distribution.ad.js) to avoid confusion, though I'm not entirely sure what to.

One obvious idea is to simply append `...Agg(regator)` onto the name of each aggregator.

Another is to rename all of the aggregators something like this:

```
histogram => count
distribution => sum
MAP => argmax
```

... though I'm not sure that's a good idea.

Any thoughts?

**Comment by stuhlmueller** [comment]
I'd go with a mix of your two proposals (but I think either on its own would be fine too):

~~~~
Distribution => ScoreAggregator
Histogram => CountAggregator
MAP => MaxAggregator
~~~

**Comment by null-a** [comment]
I like it - thanks!
