### ISSUE TITLE
Member function call broken for object literals

### ISSUE THREAD

**Issue by JsonFreeman** [probmods/webppl#406]
On the daipp branch, calling a function assigned to a property in an object literal simply returns the function, instead of the return value.

```js
var a = 
{
  b: function() { return 0; }
};

a.b(); // Returns a function
```

**Comment by stuhlmueller** [comment]
This is generally impossible, unfortunately. See #358 for a workaround.

**Comment by JsonFreeman** [comment]
Thanks!
