### ISSUE TITLE
Extra checks to smooth transition to new ERP interface

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#413]
Some significant fraction of programs/models will need to be updated as a result of the introduction of the new ERP interface. Since the reporting of errors in webppl isn't great (yet), we want to consider what simple things we can do to smooth this process.

For reference, here are what I expect will be the most common changes that need to be made to programs.

(I'm using a specific ERP here to make the examples clearer, but this applies to all ERP of course.)

##### `sample`

 `sample(gaussianERP, [0,1]) => sample(Gaussian({mu: 0, sigma: 1}))`

Note that the sampling helper functions `flip`, `gaussian`, etc. continue to work as before.

##### `score`

`gaussianERP.score([0, 1], val) => Gaussian({mu: 0, sigma: 1}).score(val)`

A special case of this is:

```
var marginal = Enumerate(thunk)
marginal.score([], val) => marginal.score(val)
```

**Comment by null-a** [comment]
One option is to add _run-time_ checks and useful errors to try and catch the the use of the old interface. In both the `sample` and `score` examples (above), programs written the old way will throw a `ReferenceError` because `gaussianERP` is no longer defined. (But not the example involving `Enumerate`.)

One thing we could try is to `catch` this specific error and print some general information about the new interface. Another idea is to define e.g. `gaussianERP`as a kind of dummy distribution so that we can detect its use with `sample` and `score` and print more fine-grained messages.

> people might write (for example) sample(bernoulli({p: .5})) instead of sample(Bernoulli({p: .5})) does highlight a real concern. 

I do think having a nice error message for this case is a good idea, but I'm not sure that by itself it helps make the _transition_ that much easier?

Another option is to do this _statically_, with a kind of webppl linter-type-thingy. It seems like we could check for the general versions of the examples above, and show the changes that need to be made when we find them. A simple version of this might not catch everything, but I image it would work OK? 

This is probably more work, but less messy and perhaps more helpful? I guess we need to decide how much effort its worth putting into this.

**Comment by ngoodman** [comment]
can we simply have `sample` check that it gets a Distribution object as input and throw a useful error if not?

i'd favor doing something very simple for now (or nothing) and making sure to think about this and other webppl-specific common errors after we merge in the better error handling.

**Comment by null-a** [comment]
> can we simply have sample check that it gets a Distribution object as input and throw a useful error if not?

We can do this of course, and I think it's helpful. However, I opened this issue in response to this comment on #412:

> This could be important to have before we merge the PR, so that the process of converting existing models to the new style will be a little less painful for users.

The point I'm trying to make here (in this issue) is that adding the suggested check doesn't seem to help *converting existing models* all that much, since existing code will throw a `ReferenceError` before ever getting to the proposed check.

> i'd favor doing something very simple for now (or nothing) and making sure to think about this and other webppl-specific common errors after we merge in the better error handling.

Fine by me. I'm not in the best position to judge how painful these changes will be for webppl users, so I'll follow the lead of those who are!

**Comment by stuhlmueller** [comment]
I agree that we should go with simple runtime checks for now, just making sure that potentially common errors (whether they stem from converting existing models or not) result in informative messages. Two that come to mind are (1) confusing `bernoulli`/`Bernoulli` and (2) using `erp.score([], value)` instead of `erp.score(value)`. Most importantly, we want to avoid a situation where a mistake like this doesn't lead to an error and instead silently produces incorrect model results.
