### ISSUE TITLE
Issue with computing on cached values and MH

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#416]
I've been porting probmods.org to webppl and I've run into an issue with this model:

```js
var dist = MH(function () {
    var strength = cache(function (person) { return gaussian(0, 1)})
    var lazy = function (person) { return flip(1/3) }
    var totalPulling = function (team) {
         return sum(map(function (person) {
            return lazy(person) ? strength(person) / 2 : strength(person)
        }, team))
    }
    return totalPulling(['bob'])
}, 10000)
dist.support().length
```

When I run with `MH`, there are way too few support states (< 10). I don't get this issue with `ParticleFilter` or `Rejection`. I also don't get problems if I do `MH` while returning `strength('bob')` (I get 10000 states)

**Comment by null-a** [comment]
`cache` assumes it is applied to a deterministic function.

Strange looking things happen if you cache a function with random choices, because the cache is shared across different executions.

I think this explains everything you're seeing here, so I'll close this issue.
