### ISSUE TITLE
Incorrect support binning when distribution is over functions

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#422]
This:

```js
var f = function(x) { return 'a' + x};
var g = function(x) { return 2 + x };
var m = function() { return flip() ? f : g }
var mDist = Enumerate(m);
mDist.support();
```

returns just `[ [Function: g] ]` but it should return `[ [Function: g], [Function: f] ]`

(This is a little bit time sensitive; we're writing a NIPS paper that would benefit from this getting fixed, though I think we could live without it)

**Comment by longouyang** [comment]
Summarizing in-person conversation with Noah:

Comparing functions is a hard problem, so many systems treat all functions the same.

One thing we might do is use the `name` property of functions for comparison (technical note: only functions declared with `FunctionDeclaration` get a name property but our generated code for functions looks like `var foo = function foo(x) { ... }` so I think we'll always be able to get `name`)

**Comment by longouyang** [comment]
Or we could do something crazy and use `f.toString()`

**Comment by stuhlmueller** [comment]
We could also just throw an error if users try to build a marginal over functions (or, more generally, over unhashable values). With solutions based on function name or code, people will run into trouble when they try things like this:

~~~~{js}
Enumerate(function(){
    var x = flip(.5);
    return function(){
        return x;
    };
})
~~~~

**Comment by null-a** [comment]
I believe this is a duplicate of #179

**Comment by longouyang** [comment]
Ah, right you are -- I'll close this oe.
