### ISSUE TITLE
Lots of recent breaking changes?

### ISSUE THREAD

**Issue by jsalvatier** [probmods/webppl#432]
I'm trying out the latest version of webppl for [webppl-agents](https://github.com/agentmodels/webppl-agents) and there seems to be a lot of breaking changes made. 

Is there a list somewhere of changes that have been made recently?

The ones I know of so far are

1. `ERP.sample()` function (which we had been using to test whether something could be sampled from) is removed and now instead there's a `dists.isDist` function. 
2. `categoricalERP` and `deltaERP` have been replaced with `Categorical` and `Delta` and have different parameter formats.
3. `ERP.score` no longer takes an array as the first parameter (so `erp.score([], x)` should change to `erp.score(x)`).
4. `Rejection()` now takes an object as the second parameter instead of a list of a number of samples. 

Without knowing what changes have been made its difficult to fix the problems these bring up because webppl doesn't have tracebacks.

**Comment by null-a** [comment]
The dev branch is the work in progress version of what will be version 0.7,
and yeah jumping in at this point will be painful. The only way to see
what's been worked on at the moment is to look at the relevant github
milestone. We'll have a full list by the time it's released in a couple
weeks time.

**Comment by null-a** [comment]
>  We'll have a full list by the time it's released in a couple
> weeks time.

I've started writing some [release notes](https://github.com/probmods/webppl/wiki/Release-notes-0.7).

 > ERP.sample() function (which we had been using to test whether something could be sampled from) is removed and now instead there's a dists.isDist function.

Distributions (the thingies that replace ERPs) still have a `sample` method, but it's probably safer to use the helper.
