### ISSUE TITLE
Address problems with binomial approximation

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#436]
Consider this simple accumulator model that samples from a binomial each time step and returns the time step when the sum exceeds a threshold. 

```
var n = 100

var accumulator = function(state, t) {
  var newState = binomial(.05, n);
  if(state + newState >= n) {
    return t;
  } else {
    return accumulator(state + newState, t+1);
  }
};

var model = function(){
  return accumulator(0, 0);
};

print(EnumerateBreadthFirst(model,  1))
```

Note that without doing breadth-first search, this will not terminate and will hit a memory error. However, using breadth-first search throws an error: ```webppl.min.js:2 Uncaught AssertionError: false == true```. Maybe this will be clearer once we have the stack traces, but the weird part is that you only get the error when `n` is set to `101` or higher. When it's `100` or less, it works as expected. I'm guessing this has something to do with the binomial approximation?

**Comment by longouyang** [comment]
Yes, the binomial approximation kicks in when n > 20, np > 5, and n(1-p) > 5.

And it's got bugs -- (e.g., `score(Binomial({n: 21, p: 0.5}), 21)` returns `-Infinity`). We should probably just ditch the approximation

**Comment by hawkrobe** [comment]
Gotcha -- I changed the title to reflect the origin of the problem. What does the approximation buy us? Is it that much more efficient?

**Comment by null-a** [comment]
Related: #219

**Comment by longouyang** [comment]
I'm not sure if the approximation buys us anything, actually.

**Comment by dritchie** [comment]
This is a hold-over from when I initially ported a bunch of "efficient" random number generators over to Javascript a long, long time ago. I've also been skeptical about whether these approximations actually matter in practice but figured that as long as things worked correctly, might as well just not touch it. Now that there's an example of it *not* working correctly, I think it'd be fine to get rid of it.

**Comment by null-a** [comment]
> And it's got bugs -- (e.g., score(Binomial({n: 21, p: 0.5}), 21) returns -Infinity). 

I'm not sure I would call that a bug, the true log prob is something like -300, so -Infinity seems like a pretty good approximation! :)

> using breadth-first search throws an error: webppl.min.js:2 Uncaught AssertionError: false == true.

I was intrigued by what exactly was happening here. It turns out that the underlying problem is that the single execution that finishes has probability zero (because of the approximation @longouyang pointed out) so it's not possible to return a normalized marginal. We [made the error message here more useful](https://github.com/probmods/webppl/commit/1cd41fdb0a7106c1b1e198ae07e1fc7083291920) a while ago, looks like that hasn't made it to webppl.org yet.

> I'm not sure if the approximation buys us anything

**Comment by null-a** [comment]
> I'm not sure if the approximation buys us anything

I don't know either. Note that the straight-forward switch to using the code in the `else` branch will pick up a different approximation, this time from `lnfact`.

**Comment by longouyang** [comment]
> I'm not sure I would call that a bug, the true log prob is something like -300, so -Infinity seems like a pretty good approximation! :)

But this is this difference between being in the support vs not, which has actually led to bugs for me.

> I don't know either. Note that the straight-forward switch to using the code in the else branch will pick up a different approximation, this time from lnfact.

The `lnfact` approximation is simpler, though, and it's also clear how to write `lnfact` exactly.
