### ISSUE TITLE
In browser, printing -Infinity displays null

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#445]
If you run this code at webppl.org, you get unexpected behavior:

```
var model = function() {
  return randomInteger(2);
};

var myERP = Rejection(model, 100);

print(myERP.score([], 3)) // => null
print(typeof myERP.score([], 3)) // => "number"
print(myERP.score([], 3) == null) // => false
print(myERP.score([], 3) == "null") // => false
```

This means models run in the browser don't properly handle factor statements for elements not in the support (``Uncaught AssertionError: Number expected.``)

The weirdest part is that the score returns null, but it doesn't behave like a null value! So there's no way to catch out-of-support elements. 

This code runs properly on my local machine for both dev and master branches, so I'm not sure what the fix would be.

**Comment by longouyang** [comment]
I think the issue has to do with how `-Infinity` is *displayed* in the browser, because this code works:

```js
var model = function() {
  return randomInteger(2);
};
var myERP = Rejection(model, 100);

myERP.score([], 3) == -Infinity // true
```

**Comment by stuhlmueller** [comment]
Replacing `print` with `console.log` shows this as well:

~~~~{js}
var model = function() {
  return randomInteger(2);
};
var myERP = Rejection(model, 100);

console.log(myERP.score([], 3))  // => -Infinity
~~~~

**Comment by stuhlmueller** [comment]
~~~~{js}
print(-Infinity)  // => null
~~~~

**Comment by longouyang** [comment]
As this is actually an issue with the browser wrapper stuff we provide in dippl, I've submitted a PR there.

**Comment by stuhlmueller** [comment]
Thanks!
