### ISSUE TITLE
Extract `cache` to a package

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#450]
This came up in the lab meeting (May 20th) on documentation.

**Comment by stuhlmueller** [comment]
See also: [webppl-dp](https://github.com/stuhlmueller/webppl-dp) package

**Comment by null-a** [comment]
My understand (from [this discussion](https://github.com/probmods/webppl/issues/448#issuecomment-225373507)) is that this can stay in core, so I'm closing this issue.
