### ISSUE TITLE
Binomial returns non-integer values for large n

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#457]
~~~~{js}
var dist = Binomial({p: .5, n: 100000});
sample(dist);  // => 49858.009765625
~~~~

**Comment by longouyang** [comment]
Some background -- we are using a sampler from an old paper by Ahrens & Dieter (1974).

We should write some sampler tests for binomial and investigating newer sampling methods.

**Comment by hawkrobe** [comment]
Agree on writing sampler tests. I'm curious, though -- can you just round to the nearest integer? I suspect it would still have the right asymptotic properties... When looking for newer sampling methods, I still think returning non-integer values is a less dangerous flaw than leaving values out of the support.

**Comment by null-a** [comment]
Also see #219
