### ISSUE TITLE
Cleanup examples folder

### ISSUE THREAD

**Issue by pedir** [probmods/webppl#48]
Add simpler examples and organize the current examples with better documentation so that they're more useful to newcomers.

**Comment by stuhlmueller** [comment]
Also, make sure the existing examples actually run.

**Comment by dritchie** [comment]
FWIW, currently, the following examples fail:

cv-pragmatics-parsing
hmm
incrementalsemparse
pcfg
pragmaticsWparsing
semanticparsing

**Comment by ngoodman** [comment]
yes, these were created while we were working on dippl, and never intended for public consumption. we should delete them and instead add some useful simple cases.

**Comment by stuhlmueller** [comment]
We could merge `/examples` and `/tests/test-data` into a single folder with wppl files which serve both purposes (testing and explanation).
