### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#484]
Flipping a coin on the command line currently takes 2.5s:

~~~~
parsePackageCode: 2072.600ms
compile: 724.353ms
run: 2.793ms
~~~~

**Comment by ngoodman** [comment]
there is also an unfortunate lag in the browser version, due to compilation. i assume this is due to compiling the header? is it possible to pre-compile the header so that it doesn't have to be re-processed each time?

**Comment by null-a** [comment]
Possibly related: #62.

**Comment by null-a** [comment]
In these simple examples the majority of the time is spent in `parsePackageCode`, and most of that is spent doing macro related things. I see a dramatic speed up if I ditch macro support:

*With macros*
```
time webppl examples/geometric.wppl --verbose
parsePackageCode: 1369.584ms
compile: 481.426ms
run: 6.358ms
real	0m2.170s
```
*Without macros*
```
time webppl examples/geometric.wppl --verbose
parsePackageCode: 39.401ms
compile: 458.663ms
run: 6.097ms
real	0m0.809s
```

I don't see any simple ways to make this faster, but my guess is that updating sweet.js (#270) would probably help.
