### ISSUE TITLE
Handle comma-separated var declarations

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#52]
e.g.,

```js
var x = flip(0.5),
    y = flip(0.7),
    z = x || y
```

**Comment by stuhlmueller** [comment]
It would be good to have a principled approach to deciding which Javascript features should be part of the webppl language, and which shouldn't (same comment applies to issue #2).

**Comment by null-a** [comment]
This appears to be working now. The full WebPPL program I tested was:

```js
var x = flip(0.5),
    y = flip(0.7),
    z = x || y;

[x, y, z];
```

A `git bisect` suggests this started working at commit 25cdd62d.

Are you happy this is fixed or does the problem only show up in a more specific setting?
