### ISSUE TITLE
Update webppl.org and dippl.org to 0.8

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#521]

**Comment by stuhlmueller** [comment]
Use CDN

**Comment by longouyang** [comment]
fa55227 is available at http://cdn.webppl.org.s3-website-us-west-2.amazonaws.com/webppl-0.8.1-fa55227.js

(I'll get cdn.webppl.org to point to this as soon as I can flag down Noah to do the DNS stuff)

**Comment by longouyang** [comment]
An alternate URL works for both HTTP and HTTPS:

https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.8.1-fa55227.js

**Comment by longouyang** [comment]
Updated in probmods/webppl@5dd8495 and probmods/dippl@1954f51
