### ISSUE TITLE
Add normalizationConstant attribute to (some) erps

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#53]
It would be useful to be able to access the normalization constant for ERPs generated by inference algorithms. For enumeration, this would be exact, whereas for particle filtering, it is an estimate. 
(We are already computing these numbers, just don't have a good way of accessing them.)

**Comment by stuhlmueller** [comment]
I notice that the particle filter in dev has a "strict" mode flag that sort-of allows this.

The flag does two things: first, it controls whether to throw an error when all particles have weight -inf, and second, it controls whether the object returned from the particle filter includes the estimated normalization constant:

    // Return from particle filter by calling original continuation:
    this.k(this.oldStore,
           this.strict ? dist : {marginal:dist, weight: this.particles[0].weight});

These two pieces of functionality should probably be decoupled.

**Comment by iffsid** [comment]
Yes, I agree. They ought to be decoupled. The only reason they weren't was for convenience.

**Comment by ngoodman** [comment]
however the current "strict" flag breaks the marginalization routine interface: ParticleFilter needs to return an ERP object. instead we should simply add an optional field to the returned ERP that records the normalizing constant estimate.... (though strictly speaking this isn't a property of the ERP itself.)

**Comment by stuhlmueller** [comment]
I changed this in 87b7818d16417e23a1939585342d7321d16c02a1. Now, the interface is the same with "strict" flag, and the normalization constant is stored as erp.normalizationConstant for the returned erp.
