### ISSUE TITLE
Mean-field with uniforms gives -Infinity guide log probability

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#534]
E.g. this program:
```javascript
var model = function(_xs, _ys) {
  var xs = _xs || [1,2,3];
  var ys = _ys || [4,5,6];
  var m = uniform(-10, 10);
  var b = uniform(-3, 3);
  
  // TODO: sample sigma^2 from inverse-gamma
  var noiseDist = Gaussian({mu: 0, sigma: 1});
  
  var score = sum(map2(function(x,y) {
    var yhat = m*x + b, dev = y - yhat;
    return noiseDist.score(dev*dev)
  }, xs, ys))
  
  factor(score);
  
  return {m: m, b: b}
}

Optimize(model, {steps: 10})
```
produces this error:
```
ELBO: scoreDiff is not finite.
```
When `guide.independent` initializes the parameters for a mean-field approximate guide distribution, those parameters get value 0 (or `squishFn(0)`, if they are bounded), due to how Tensors initialize. This means that a `uniform` distribution has both its lower and upper bound parameters initialized to zero, which is a problem.

One way to get around this: change guide.independent so that it initializes parameters to the values used by the prior distribution. Are there any compelling reasons why this wouldn't be a good idea?

Also: I don't think it makes sense to use `uniform` as a guide distribution. The distribution can't be shaped, and the bounds are often used to specify inviolable range properties of the data, not tweakable parameters. I think the right thing to do here might be to make another special case (like `dirichletSpec` in `guide.js`) so that `uniform` actually uses a scaled `beta` as its guide distribution. This would require injecting additional transformation code, not just swapping out the dist, so that makes it a bit trickier to handle...

**Comment by null-a** [comment]
Yeah, guiding `Uniform` with a 'shapable' distribution is on my to do list.

> Are there any compelling reasons why this wouldn't be a good idea?

I considered it, but held off adding it because I couldn't see much benefit. Once we use a `Beta` to guide the `Uniform` the end points will no longer be parameters, so we won't have this situation where there's a constraint that says one parameter must be strictly greater than another?
