### ISSUE TITLE
Encapsulate more error info inside Error objects, rather than use console.log / console.error

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#541]
In several error scenarios, WebPPL both throws an `Error` object and prints something to the console via `console.log` or `console.error`. For example, when `Enumerate` encounters a distribution with non-finite support, or when any of the source transformations fails (see `fail` in `syntax.js`). I bring this up because only the contents of the `Error` object are surfaced to the user when using `webppl-editor` (unless the user has the browser console open, and even then it can be hard to correlate what's printed there with what's printed under the editor). At least in both the cases I cited, having the extra console information at hand is critical in pinning down where the error occurred. It would be good to make a systematic pass through all the error-case uses of `console.log` and `console.error` and see if we can't encapsulate that info inside the `Error` object.

**Comment by longouyang** [comment]
FWIW, inside `webppl-editor`, I plan to hijack the console methods so that their output also appears in the results boxes.

**Comment by dritchie** [comment]
Cool, that sounds like it would do the trick :)

**Comment by longouyang** [comment]
I just landed this in editor 0.9.2:

![screen shot 2016-07-08 at 6 17 26 pm](https://cloud.githubusercontent.com/assets/14802/16705237/6791a5b0-4538-11e6-8bf0-cd402338a951.png)

(demo page is at http://probmods.github.io/webppl-editor/)

**Comment by dritchie** [comment]
Yep.
