### ISSUE TITLE
Show warning when Infer/Optimize receive unexpected parameter

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#542]
This is useful because unexpected parameters likely arise because of typos, mis-remembering param names, interface changes etc. Sometimes the effects are subtle and go unnoticed. A warning would help guard against this.

For example `Infer({method: 'enumerate', maxexecutions: n}, model)` should print something like `Infer: Unrecognized option "maxexecutions"`.

**Comment by ngoodman** [comment]
especially pernicious when you have to pass a param at the correct level to make it work.

eg. `{method: 'optimize', stepSize: .01}` vs `{method: 'optimize', optMethod: {adam: {stepSize: .01}}}`.
