### ISSUE TITLE
Example on homepage doesn't work

### ISSUE THREAD

**Issue by chrisranderson** [probmods/webppl#545]
Using Chrome: Version 50.0.2661.18 dev (64-bit) on Ubuntu 14.04

![image](https://cloud.githubusercontent.com/assets/5461398/16734186/d5719486-4741-11e6-8760-efd2ca7a120c.png)

**Comment by null-a** [comment]
How odd! I'm not seeing why your code would cause _that_ error. Your program will cause an error because `Enumerate` no longer takes a number as its second argument, but the message you're getting is unrelated to that. To start to pin this down, it might be useful if you could:

1. Make sure a super simple program works.
2. Try your failing example again, but immediately after a page refresh.

**Comment by chrisranderson** [comment]
Sorry, I guess I had stuff in localStorage that was old or something. I get the same error if I open the homepage in an incognito window, though:

![image](https://cloud.githubusercontent.com/assets/5461398/16741394/4f2bac30-4760-11e6-8380-e9ba2521f788.png)

**Comment by null-a** [comment]
> Sorry, I guess I had stuff in localStorage that was old or something

Even if you did, there's still a bug I think!

It works fine for me in incognito mode. I'm not sure what's going here, so I'll have a think about it.

Thanks for trying those things out and reporting the original problem.

**Comment by chrisranderson** [comment]
Fwiw, I get the same error on this page: http://probmods.github.io/webppl-viz/

**Comment by longouyang** [comment]
That editor error is not related.

As of today, the latest stable Chrome is 51.0.2704.106 -- could you try updating and see if you still get the bug?

**Comment by chrisranderson** [comment]
I ran it in Chrome on my phone: 51.0.2704.81 and it runs fine. Not sure how to update Chrome on Linux - it is the unstable/dev channel, and it looks like updates aren't available.

**Comment by longouyang** [comment]
Do you use any Chrome extensions? If so, could you try disabling them?

**Comment by chrisranderson** [comment]
None of them are allowed in incognito mode, and that still doesn't work. I also tried disabling them and trying it in a normal tab - same error.

**Comment by null-a** [comment]
Just so I'm clear what's happening, do all program fail with that error?

Trying to run one of the failing programs directly from the JS console might be informative. Could you try something like this:

```js
webppl.run('1+1', function(s,v) { console.log(v) })
```

**Comment by chrisranderson** [comment]
![image](https://cloud.githubusercontent.com/assets/5461398/16817267/41cc3ba4-48ff-11e6-86cf-a7ecfbd4ee19.png)

Yep, everything seems to fail that way.

**Comment by chrisranderson** [comment]
Some sweet.js thing?

https://github.com/sweet-js/sweet.js/issues/223

**Comment by null-a** [comment]
Thanks for trying that, it's useful.

Yes, the error is related to macros, but the question is why do you get an error with a program I can just fine (`1+1`) when we're both supposed to be using the same version of webppl?

I would have guess that there was some state on your machine that was messing things up, but the fact that you also have the problem in incognito mode seems to rule out all of the stateful stuff I can think of. (We also know that incognito mode works for me.)

I just tried webppl.org on Ubuntu+Chrome on my old laptop. The version of Chrome I had installed gave me an error, but not the one you're seeing. Upgrading to the latest Chrome fixed that problem and appears to work fine.

It's probably worth trying @longouyang's suggestion of updating Chrome at point if you haven't already.

**Comment by chrisranderson** [comment]
I removed Chrome, installed the stable channel and everything works fine. We may never know!
