### ISSUE TITLE
Make adam the default Optimize method

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#548]
Any objections to doing this? It's default behavior is (in my experience) always more stable than adagrad.

**Comment by null-a** [comment]
That you think it's *always* more stable is surprising to me, but perhaps I just haven't been paying enough attention! In the absence of examples I can point to where adagrad does better, I'm fine with switching.

**Comment by dritchie** [comment]
Well, I certainly can't *prove* it's always more stable. But in every example I've tried, it does a better job of (a) keeping the gradients stable without (b) squashing them too much and leading to slow convergence.

**Comment by null-a** [comment]
Do you have an opinion about what the default step size for adam should be? (webppl uses the default specified in adnn.) I did a little informal testing on some simple daipp models and for those it seemed that the current default of 0.1 was too large, and that 0.001 would be much better. This value is also mentioned in the original paper as been generally suited to the models they experimented on.

**Comment by dritchie** [comment]
The default value in adnn isn't particularly meaningful, so I'm happy to go with 0.001 if that's what your experiments (and the original adam paper) suggest.
