### ISSUE TITLE
Some distributions missing helpers

### ISSUE THREAD

**Issue by chrisranderson** [probmods/webppl#557]
Missing the lowercased helper functions: 

- DiagCovGaussian
- DirichletDrift
- GaussianDrift
- LogisticNormal
- MultivariateBernoulli
- TensorGaussian
- UniformDrift

I can submit a PR with these functions added, if you'd like. I was planning on making a note in the docs about the helper functions, saying that all of the distributions had a corresponding helper function.

**Comment by null-a** [comment]
Thanks for opening this. I'll be doing something about helpers for drift kernels as part of #119. I agree it makes sense to have helpers for the rest of the distributions for consistency. If you tackle this, it would be good to exercise the new helpers in the tests. For most of the distributions in your list we have simple tests to check sampling works ok (e.g. [`tensorGaussian.wppl`](https://github.com/probmods/webppl/blob/7c24e1543cd6ddfc875d48161eeb1db9b5d2bd67/tests/test-data/stochastic/models/tensorGaussian.wppl)), it would be sufficient to switch those to use the new helpers I think. Don't worry about testing `LogisticNormal`.

**Comment by chrisranderson** [comment]
Okay, so I'll write functions for DiagCovGaussian, MultivariateBernoulli, TensorGaussian, and LogisticNormal but only tests for the first three.
