### ISSUE TITLE
Ignore factors outside of inference, rather than throw an error.

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#56]
Is there a compelling reason to throw an error for factor statements that are hit when the program is running outside of inference? My usual interpretation of this situation has been to silently ignore the factors. Otherwise, the programmer has to tweak the program (i.e. comment out some lines) depending on whether they're just running it forward for testing or running it through an inference coroutine.

**Comment by ngoodman** [comment]
The decision was based on wanting consistent semantics (so that factor wouldn't sometimes silently not do anything). On the other hand it is kind of annoying for debugging forward models.... We could switch it to a warning instead of error, or make a permissive mode.

**Comment by stuhlmueller** [comment]
Now that we have [a forward sampling inference algorithm](http://docs.webppl.org/en/master/inference/methods.html#forward-sampling), the motivation for this PR seems to be addressed.
