### ISSUE TITLE
Potentially confusing error message: "Assignment is allowed only..."

### ISSUE THREAD

**Issue by chrisranderson** [probmods/webppl#567]
With the program:

```javascript
a = [1, 2, 3]
b = [4, 5, 6]
append(a, b)
```

I get the error message "Assignment is allowed only to fields of globalStore."

If that error message is true, then this would be illegal:

```javascript
var a = [1, 2, 3]
```

It looks like it's because it's making a global assignment since `var` is missing.  Maybe instead the message could be something like "Assignment in the global scope can only be to the globalStore variable."

**Comment by null-a** [comment]
The error is correct, `var a = [1, 2, 3]` is a variable declaration rather than an assignment. That's not to say the error can't be improved! Perhaps we cover the case you highlight by adding something like "Perhaps you meant `var a = foo`" when we catch `a = foo`

**Comment by longouyang** [comment]
Closed by #576
