### ISSUE TITLE
Default VI guide for sigma param of gaussian can produce negative numbers

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#572]
This seems to just work for VI, which is surprising, as `gaussianScore` and `gaussianSample` appear to assume that `sigma` is positive.

Relatedly, I'm trying to compare VI with a particle filter and `ParticleFilter` chokes on negative `sigma`:

```js
var modelPF = function() {
  var p = Math.min(0.999,
                   Math.max(0.001,
                            gaussian({mu: 0.09999999727834619, sigma: 0.09999999682285558})));
  var B = Bernoulli({p: p});
  factor(sum(map(function(d) { return B.score(d) }, data)));
  return p;
}

ParticleFilter(modelPF)
```

The result is filter collapse:

```
Marginal:
    0.2389592078909717 : 1
```

If I fix up `gaussianScore` and `gaussianSample` to use `Math.abs(sigma)` then things work okay:
```
Marginal:
    0.001 : 0.182
    0.19682490339732983 : 0.001
    0.02421690743015055 : 0.001
    0.2048213966446087 : 0.001
    0.11473485847969342 : 0.001
    ...
```

So a couple questions:
1. Why doesn't VI hit an error when the guide uses a negative `sigma`?
2. Should we fix `gaussianScore` and `gaussianSample` to use `Math.abs(sigma)`? (or maybe `var _sigma = (sigma < 0) ? -1 * sigma : sigma` for greater AD-friendliness?)

**Comment by null-a** [comment]
All our variational parameters are unconstrained numbers, but we pass them through squishing functions before passing them to distributions so as to respect any constraints on the distribution's parameters. So, the automatic guide generated for a Gaussian is something like:

```js
var guideMu = scalarParam()
var guideSigma = Math.exp(scalarParam())
var guideDist = Gaussian({mu: guideMu, sigma: guideSigma});
sample(Gaussian(params), {guide: guideDist})
```

If you look at the raw params (returned by `Optimize` for example) then yeah, the parameter might be negative, but it won't be when it reaches the guide Gaussian. Does that help?

>  Should we fix gaussianScore and gaussianSample to use Math.abs(sigma)

I think Gaussian should just complain on sigma < 0. I consider this to be part of #332.

**Comment by longouyang** [comment]
Could we make `Optimize` emit the squished params? It'd be nice if its output was directly interpretable.

At any rate, I think we can close this.

**Comment by dritchie** [comment]
> Could we make Optimize emit the squished params? It'd be nice if its output was directly interpretable

Not directly, no--the output of Optimize needs to be something can be passed as the `params` option to forward sampling or SMC, and those algorithms will in turn pass them through the squishing functions again (the squishing function is part of the guide program). I agree that interpretable parameters would be nice, though.
