### ISSUE TITLE
Add a marginalize helper function

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#614]
It's often very helpful to project out individual components of a posterior

**Comment by null-a** [comment]
Do you mean add something like this:

```js
var marginalize = function(dist, project) {
  return Infer({model() {
    return project(sample(dist));
  }});
};
```

**Comment by longouyang** [comment]
Yes, but could the implementation be made more efficient by iterating through `dist.support()` rather than using `Infer`?

**Comment by null-a** [comment]
Probably, though I'm not sure there's a huge amount of overhead from `Infer` we can easily avoid. (e.g. we'd still be doing lots of (de)serialization, CPS.) If the straight-forward implementation is too slow thought (is it?) I guess we should just try it.

**Comment by longouyang** [comment]
Okay, I'll just submit the `Infer` version as a PR then.

**Comment by null-a** [comment]
Thought about naming: In my mind `Marginal` (Noah's original suggestion) is still a good name for the thing that `Infer` does, and I'm kinda nervous that this quite close to that. But since we never did add `Marginal` as an alias for `Infer`, I guess this isn't a problem.

**Comment by longouyang** [comment]
Actually, given the way that you wrote it, we might want to call it `mapDistribution`.
