### ISSUE TITLE
Inconsistencies / bad error messages with underscore.js

### ISSUE THREAD

**Issue by tbenst** [probmods/webppl#615]
Underscore.js convention is to give the list as the first parameter and a function as the second (see map, reduce, filter, etc.). Webppl has this reversed which is somewhat confusing when switching between the two.

Additionally, webppl gives a very nondescript error message if _.map or _.reduce is called

**Comment by null-a** [comment]
Thanks for this! I've split this out into issues #624, #625 and #626.
