### ISSUE TITLE
Consider switching the order of map's parameters

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#624]
This might be worth considering since writing this:

``` js
map(data, function(x) {
  // blah...
  // blah.
  return f(x);
})
```

... makes it a little easier to pick out what is been mapped over compared to:

``` js
map(function(x) {
  // blah...
  // blah.
  return f(x);
}, data)
```
- The somewhat work-in-progress `mapData` currently looks like the first of these for this reason.
- Something similar would apply to the other higher order header functions.
- This may become moot after #358?

**Comment by chrisranderson** [comment]
Agreed it would be easier to read this way, but convention (fwiw) seems to be that the function is the first parameter:

https://clojuredocs.org/clojure.core/map
https://docs.python.org/2/library/functions.html#map
http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:map

**Comment by stuhlmueller** [comment]
Yes - see also the table of [map in different languages](https://en.wikipedia.org/wiki/Map_(higher-order_function)#Language_comparison).

**Comment by null-a** [comment]
There doesn't seem to be much support for this idea, so I'm closing the issue.
