### ISSUE TITLE
Choices get credit for earlier costs

### ISSUE THREAD

**Issue by insperatum** [probmods/webppl#637]
In the current implementation, the LR portion of the ELBO objective awards the same credit to each random choices in a program (i.e. the final _scoreDiff_). This means that gradient estimators for late decisions have a much higher variance than they need to, because they take credit for everything that came beforehand, and so variational inference is much much slower.

```javascript
var model = function() {
  sample(Gaussian({mu: 0, sigma: 0.1}), {guide: Gaussian({mu: 0, sigma: 10})})
  sample(Gaussian({mu: 1, sigma: 0.1}), {reparam: false}) //guide params to be learned
}
var params = Optimize(model, {steps: 10000});
//Learns mu=0.18397 rather than mu=1
```

I made a commit which corrects this: https://github.com/insperatum/webppl/commit/509bd4e74373f1cba07990d93e2695f4e0f573fa

```javascript
var params = Optimize(model, {steps: 10000});
//Learns mu=0.9903
```

How does it look? Can I submit a PR?

**Comment by null-a** [comment]
Ah... I also have a [branch](https://github.com/probmods/webppl/tree/new-vi-estimator) that includes this change. Take a look at this new version of the [ELBO estimator](https://github.com/probmods/webppl/blob/new-vi-estimator/src/inference/elbo2.ad.js). In addition, it uses the hint we get from `mapData` to play a similar trick for conditionally independent random choices. I think we could merge this into dev as soon as everyone is convinced it's correct. (And we've renamed `elbo2.js` to `elbo.js`.) Sorry you didn't know about this!

**Comment by insperatum** [comment]
Ah great, no worries! Anything I should know about that before I use it?

**Comment by null-a** [comment]
The only other thing is that it also has the option of doing average baseline removal. (Per random choice, for non-reparam trick choices.) This is currently turned off by default -- enable it with something like [this](https://gist.github.com/null-a/a1c227fa92bc1115ff7540cecb756118#file-lda-js-L49).

Other than that, this is supposed to be a drop in replacement for the current implementation. (I think the only thing it's missing is the warning we issue when auto-guides are used.)
