### ISSUE TITLE
Change npm tagging strategy to create tags on master?

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#638]
Currently, we're running [`npm version`](https://docs.npmjs.com/cli/version) on `dev` as part of [our npm update process](http://docs.webppl.org/en/master/development/npm.html). This bumps the version number in `package.json` and creates a new git tag. Doing this on `dev` is unsatisfying, since it causes the [release tags](https://github.com/probmods/webppl/tags) point to `dev`. On `master`, the tag [commits](https://github.com/probmods/webppl/commits/master) confusingly happen before the corresponding merges. This makes it more difficult to automate building/naming the CDN bundles.

Originally, I chose this strategy since I didn't want any work to happen on `master`. If we simply adjusted the strategy to run `npm version` there, we would have to merge the changes to `package.json` back into `dev`. Maybe there is a more elegant solution, though. For example, we could split up the work that `npm version` does into a step that happens on `dev` (updating `package.json`) and a separate step that creates a git tag that points to `master` after we've merged.

**Comment by longouyang** [comment]
Can we just run `npm version` on `master` after merging `dev`?

**Comment by longouyang** [comment]
Actually, in the interest of having a working process for now, could we actually just run `npm version` on `master` after merging `dev` into it, and then merge `master` back into `dev`?

I realize it's inelegant but it's a pretty small delta from what we currently do and is a decent stopgap until someone figures out the elegant thing.

**Comment by stuhlmueller** [comment]
I'll give it a try next time I update npm.

**Comment by stuhlmueller** [comment]
I just tried the new tagging strategy. Let me know if the result is more suitable for your purposes! If it is, I'll update the explanation in the docs on how to publish a new npm package.

**Comment by longouyang** [comment]
Yes -- the result is definitely better, as what is advertised as 0.9.4 on the CDN actually contains all the work from `dev` for that release.
