### ISSUE TITLE
Do we support variational parameters that affect p, not q?

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#645]
Using webppl `v0.9.2-224e756`, if I run this program...

~~~~
Optimize(function(){
  var p = scalarParam(0.5, 0.01);
  var dist = Bernoulli({ p: p });
  factor(dist.score(true));
}, { estimator: 'ELBO', steps: 500, stepSize: 0.01 });
~~~~

...I observe:

~~~~
AssertionError: false == true
    at /Users/stuhlmueller/Projects/webppl/src/inference/elbo.js:52

51|                 if (useLR) {
52|                     assert.ok(ad.scalar.peq(typeof this.logp, 'number'));
    ---------------------------^
53|                 }

    at /Users/stuhlmueller/Documents/variational-p.wppl:4

3|   var dist = Bernoulli({ p: p });
4|   factor(dist.score(true));
   --^
5| }, { estimator: 'ELBO', steps: 500, stepSize: 0.01 });
~~~~

I can work around this issue by adding an (unused) Gaussian sample statement:

~~~~
var params = Optimize(function(){
  var p = scalarParam(0.5, 0.01);
  var dist = Bernoulli({ p: p });
  factor(dist.score(true));
  gaussian(0, 1);
}, { estimator: 'ELBO', steps: 5000, stepSize: 0.01 });
~~~~

The inferred parameter for `p` is quickly outside of the Bernoulli support (`147.23...`):

~~~~
ELBO: Defaulting to mean-field for one or more choices.
ELBO: Using PW estimator.
Iteration 0: -0.8759664489098096
Iteration 1124: 3.6394054480618903
Iteration 2200: 3.7866254945306763
Iteration 3427: 4.9173863063476695
Iteration 4592: 5.117896807780068
[[{"dims":[1],"length":1,"data":{"0":147.23326421681344}}],[{"dims":[1],"length":1,"data":{"0":-0.08544954022248888}}],[{"dims":[1],"length":1,"data":{"0":0.8333462012698061}}]]
~~~~

To what extent do we want to support optimization of parameters that affect the program, not the guide?

**Comment by dritchie** [comment]
Hmm, it looks like maybe the `'ELBO'` estimator doesn't support this? The `'ELBO2'` estimator (in the `new-vi-estimator` branch) definitely does, and we do plan to merge this into dev once the DAIPP tech report is done and the state of things is more settled (or perhaps sooner)? @null-a might know more.

As for the parameter being outside the support: just wrap the `scalarParam` call in a squishing transform (e.g. `ad.scalar.sigmoid`) to enforce support.

**Comment by stuhlmueller** [comment]
Nice, thanks! I'll try to use the `new-vi-estimator` branch for now then.

Is the plan to keep supporting parameters that affect `p`? @null-a, @ngoodman?

**Comment by dritchie** [comment]
I think almost certainly less--'model learning' is a pretty central part of the DAIPP tech report, anyway.

**Comment by null-a** [comment]
I agree this is something we need to make a decision about.

One thing that's not so good about allowing it, is that programs written this way only work with `Optimize`. However, if we choose not to allow this, then you'd probably do MAP instead, and by putting a prior on the parameter you'd have a full model that would then work everywhere. (Well, except with `Enumerate` perhaps.) This seems nice in principle, even if it's not so useful in practice. (Though getting some regularization might often be a good thing?)

**Comment by dritchie** [comment]
Hmm, yes, that is a good point--every other inference method forces you to be "fully Bayesian." I guess it depends on how philosophically attached we are to that perspective. I tend to think that being able to do maximum likelihood (w/ regularization) when you want it would be a *plus* for the system.
