### ISSUE TITLE
Add javascript files necessary to run code from http://agentmodels.org/

### ISSUE THREAD

**Issue by russellcthomas** [probmods/webppl#649]
Today, the compiler/interpreter on http://webppl.org will not run *all* code on http://agentmodels.org/ because of "dependencies" such as "dp.cache" in the "Bob and Alice Schelling Coordination game" in http://agentmodels.org/chapters/7-multi-agent.html.

What I would like is the full functionality of http://webppl.org 's interactive editor/compiler/interpreter/listing (especially creating/saving/opening files) and also to be able to run code from all of http://agentmodels.org/.

Apparently this only requires adding the dependent javascript libraries to http://webppl.org, so I presume that it is an easy change.  Alternatively, it would be nice if there was an interactive way to add javascript libraries as needed.

I need this functionality to support an interactive presentation/tutorial I am giving in October.

**Comment by stuhlmueller** [comment]
Thanks for the feedback! We should probably add an editor page to agentmodels.org. I created [an issue](https://github.com/agentmodels/agentmodels.org/issues/37) there.
