### ISSUE TITLE
Warning: Failed prop type

### ISSUE THREAD

**Issue by russellcameronthomas** [probmods/webppl#656]
I'm seeing this error in the Javascript error console (Safari):

`Warning: Failed prop type: Invalid prop 'codeMirrorInstance' of type 'function' supplied to 'CodeMirror', expected 'object'.`

I get the same error when I load pages from agentmodels.org (http://agentmodels.org/chapters/3-agents-as-programs.html) and also my cloned/modified version.

The interactive code editor box still works, so I'm not sure how severe this warning/error is.

**Comment by longouyang** [comment]
This is just a warning in a library that the editor relies on (and an incorrect one, at that). I've been trying to get the library maintainer to merge a fix to this for a while, but it hasn't happened yet. You can ignore this.

**Comment by russellcameronthomas** [comment]
OK. Thanks.
