### ISSUE TITLE
Decide whether to support directly parameterizing target programs

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#659]
If you have parameters flowing directly in to the target, then optimizing the ELBO corresponds to doing maximum likelihood for those parameters (and VI for the rest). The problem is that programs written this way won't work with any of the other inference algorithms.

The alternative is to specify a prior distribution for the parameter and guide it with a `Delta` distribution. The program is now amenable to inference with other algorithms, and optimizing the ELBO corresponds to MAP estimation.

There are at least 3 approaches we could take:

1. Officially support directly parameterizing the target. Make sure it works, document it, etc.
2. Keep it working, but keep quite about it.
3. Don't allow it. Throwing an error when this happens might help catch bugs, but I'm not sure it's straight-forward to achieve.

(Some [previous discussion](https://github.com/probmods/webppl/issues/645).)

**Comment by null-a** [comment]
I lean towards option 2, or 3 if it's do-able. It seems to me to be important to be able to use as many inference strategies with as many programs as possible.

If MAP estimation was always preferable to ML, then we wouldn't loose anything by suggesting/enforcing that programs are written this way? I guess one potential snag for the guide with `Delta` approach is the case where the shape of the prior is such that the density is unbounded. Instead of providing regularization, such a prior would force the parameter ever closer to the singularity. (Is that right?)

Another reason is that I think I find having only the guide parameterized easier to think about.

**Comment by ngoodman** [comment]
I lean toward 2 for now. I think having only the guide parameterized is easier to think about and maintain, and is the more coherent Bayesian thing. But sometimes it's quicker just to write the direct MLE version. In general I think the Delta/MAP motif is a good alternative; we could possibly add a helper (`modelParam` or something) that wraps this up to make less code.

Also note that we could recover MLE from the guide-params-only approach by adding an improper `UniformReal` distribution (that doesn't have a sampler method). A Delta-guided UniformReal param gives MLE.

**Comment by null-a** [comment]
We (@dritchie, @ngoodman and I) chatted about this and though Noah's suggest was good. This is now #664.
