### ISSUE TITLE
Merge new ELBO estimator

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#661]
The code in the [`new-vi-estimator` branch](https://github.com/probmods/webppl/tree/new-vi-estimator) is close to been ready to merge. Still to do:

* [x] Rename `ELBO2` to `ELBO`.
* [x] Minor clean-ups, as documented in code with `TODO` comments.
* [x] Maybe add back the message suggesting step size be reduced when things blow up.
* [x] Update docs.
* [x] Switch baselines on by default.
* [x] Ensure that the the use `fs` browserifys OK. (I think it will be fine.) Have these fail in a graceful way if an attempt is made to use them in the browser?

**Comment by ngoodman** [comment]
great! would be good to merge soon, so that new people we're getting up to speed have fewer branches to track.

**Comment by null-a** [comment]
Sure thing, I'll take care it. I'll aim to open a PR this week or early next.
