### ISSUE TITLE
Have mapData return undefined when sub-sampling data

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#662]
At present `mapData` returns an array with length equal to its `batchSize` param when doing mini-batches. This isn't ideal, mostly because it means the length of an array in user code changes when the inference strategy changes, which is odd. (Perhaps there's also a chance to break the correctness of mini-batches by having downstream choices depend on some aggregate of the mini-batch? Though this seems super unlikely to occur in practice.)

One idea that's been discussed is to add a new function called something like `forEach` which behaves like the current `mapData` except that it returns `undefined`, which would usually be OK since we're often interested in the side-effects of `factor`/`observe`. We'd then remove mini-batch support from `mapData`. This avoids the problem(s) mentioned above.

One snag with this approach is that if you want to use mini-batches during optimization, and then sample and return all per-datum random choices using the optimized parameters, you have to set your program up to conditionally do `mapData` or `forEach` as appropriate, and this seems like a drag.

So instead, perhaps we simply have `mapData` return `undefined` when doing mini-batches? This will often flow directly into the return value of the program (I imagine), so been `undefined` during optimization isn't a problem, and sampling without mini-batches from an optimized guide will do the right thing. It would still be odd that `mapData` returns a very different thing when the inference strategy changes, but this way might be slightly better/safer than what we have now?

**Comment by ngoodman** [comment]
> So instead, perhaps we simply have mapData return undefined when doing mini-batches? 

this seems like a good proposal for now.

our future treatment might also depend on how we end up getting at the data when doid dream learning...
