### ISSUE TITLE
Add nneval

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#663]
This only exists in daipp at present.

**Comment by ngoodman** [comment]
worth adding now as-is.

also worth figuring out how to make nn declaration and use more consistent with direct param use.

**Comment by null-a** [comment]
> also worth figuring out how to make nn declaration and use more consistent with direct param use.

There's a pattern I've started to use that might suggest one possible way to approach this -- I've [described it here](https://gist.github.com/null-a/a42a855efbce27da1f8c4f4248ddd790). I'm not sure this hits the mark, but I figure it's worth sharing at least.

**Comment by null-a** [comment]
After chatting with @stuhlmueller (Noah's on board too) it was agreed that we'll not add this (#752), and instead work towards standardizing on #710.
