### ISSUE TITLE
Operator precedence - possible parser issue

### ISSUE THREAD

**Issue by kolchinski** [probmods/webppl#668]
In the course of using WebPPL for Psych 204 at Stanford, I ran into this unexpected behavior that clashes with JavaScript operator precedence rules:

The following function returns `false`

```
var foo = function(g, x, y){
  return g(x,y) > x+y ? "yes" : "no"
}

foo(function(x,y){3*x*y},2.6,1.2)
```

However, this returns `true`, as it should

```
var bar = function(g, x, y){
  return g(x,y) > x+y
}

bar(function(x,y){3*x*y},2.6,1.2)
```

and the parentheses make it return `"yes"` as it should:

```
var baz = function(g, x, y){
  return (g(x,y) > x+y) ? "yes" : "no"
}

baz(function(x,y){3*x*y},2.6,1.2)
```

**Comment by null-a** [comment]
Good catch, thanks!

It looks like we inherit this bug from sweet.js. [I expect](https://github.com/probmods/webppl/issues/270#issuecomment-251433722) we'll remove sweet.js as a dependency in the near future which should fix this.
