### ISSUE TITLE
Add matrix primitives

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#67]
This will allow us to add n-dimensional (matrix) versions of the regression examples, test sparse regression, etc.

**Comment by null-a** [comment]
We have some functions to do vector arithmetic in [variational inference](https://github.com/probmods/webppl/blob/variational/src/inference/variational.js#L247), it would be nice to extract those.

Is the idea to use an existing library for this? (Assuming something good enough exists.)

**Comment by pedir** [comment]
I looked into different existing libraries, Noah's GP caching uses http://sylvester.jcoglan.com and I also started to use that for implementing multivariate Gaussian. The Sylvester library and its documentation look find but it hasn't been maintained actively for a while. 

There's another alternative which is seems more well-maintained: http://mathjs.org but a lot of stuff in that library aren't directly useful to webppl.

**Comment by pedir** [comment]
I actually refactored my implementation from Sylvester to Numeric (http://numericjs.com). I liked that in numeric you can just do the computation on raw js arrays without specifically creating a matrix or vector. Multivariate branch (https://github.com/probmods/webppl/tree/multivariate) is using it right now to implement a Multivariate Gaussian ERP. I'll add more testing and multi-dimensional regression examples which will perhaps rely more on Numeric (or some better alternative if there's any).

**Comment by pedir** [comment]
We now have Numeric as a dependency which looks like a decent matrix library. Multivariate Gaussian ERP is currently implemented based on that.
