### ISSUE TITLE
Reconsider whether we want to represent vectors as rank 2 tensors

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#671]
I originally chose this representation as it made matrix-matrix, and matrix-vector multiplication easy to implement and simple to use. It seems increasingly clear that this wasn't the best choice. In practice matrix multiplication is used infrequently in webppl programs (thus far), but the inconvenience caused by having to think about the trailing dimension is significant. e.g. specifying vector valued guide parameters, reshaping the output of an adnn net when writing neural guides.

Extracted from [this comment](https://github.com/probmods/webppl/issues/501#issuecomment-241809897) on #501.

**Comment by ngoodman** [comment]
yes. i think its more standard in scientific math libraries to represent vectors as Nx1 tensors. (isn't matrix-vector multiply just a matrix multiply for MxN X Nx1?) maybe i don't understand why this makes matrix multiply harder?

**Comment by null-a** [comment]
Maybe the title is misleading here...  At present vectors *are* Nx1 tensors, and matrix-vector multiplication is simple because it is just matrix-matrix multiplication. I'm suggesting we consider switching to vectors as N tensors.

**Comment by ngoodman** [comment]
oh, i see. do you have a couple of examples of things that would be cleaner if vectors were dim N?

**Comment by null-a** [comment]
The two mains things I have in mind are:

* The mismatch between the output of an adnn net (N tensor) and vector parameters of webppl distributions (Nx1 tensors). Because of this you have to write code to reshape the tensor. e.g. [`tensorToVector`](https://github.com/probmods/webppl-daipp/blob/6c15bbde0b09bf3aa5e82b2d805c9eaca50dbe2f/examples/ldaWithGuide.wppl#L199) here.
* We often have to specify the extra dimension in code, which seems like unnecessary busy work. e.g. `param({dims: [n,1]})`

**Comment by null-a** [comment]
> The mismatch between the output of an adnn net (N tensor) and vector parameters of webppl distributions (Nx1 tensors).

This isn't a problem with webppl-nn, and overall I don't think there's much value in making the change suggested here, so I'm closing this issue. We can of course re-open if need be.
