### ISSUE TITLE
Add laplace distribution

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#672]
...because it makes sparse regression easy to express. This should be straightforward since it's basically two exponentials, and we do have Exponential already.

Also we should add re-parametrizations for Laplace and Exponential for ELBO (might already for the latter?).

**Comment by dritchie** [comment]
Yep, Exponential already supports the reparameterization trick.

**Comment by null-a** [comment]
A distribution over tensors where each element is independently Laplace distributed might also be useful. i.e. The Laplace analog of `TensorGaussian`.
