### ISSUE TITLE
Unexpected behavior for _.extend inside Infer

### ISSUE THREAD

**Issue by mhtess** [probmods/webppl#679]
Consider world states that are objects

~~~~
// possible world states
var states = [
  {inContext: 0, inGeneral: true},
  {inContext: 1, inGeneral: true},
  {inContext: 2, inGeneral: true},
  {inContext: 0, inGeneral: false},
  {inContext: 1, inGeneral: false},
  {inContext: 2, inGeneral: false}
];

var statePrior = function() {
  uniformDraw(states);
}
~~~~

I would expect 

~~~~
var model =  Infer({method:"enumerate"}, function(){
    var state = statePrior();
    var scope = scopePrior();
    return _.extend(state,  {scope: scope})
});
~~~~
To behave the same as :

~~~~
var model =  Infer({method:"enumerate"}, function(){
    var state = statePrior();
    var scope = scopePrior();
    return {
            state_state: state.inContext, 
            state_inGeneral : state.inGeneral, 
            scope: scope
    }
});
~~~~

But the former seems to fail to return the prior. This remains to be an issue for `method: "forward"`

**Comment by stuhlmueller** [comment]
`_.extend` mutates its first argument, which can cause problems for enumeration where the same variable (i.e. at the same memory location) may be shared across executions. Try `return _.extend({}, state,  {scope: scope})`?

**Comment by mhtess** [comment]
That does seems to work. What I don't understand about your explanation is that the marginal distribution on the `state` variable seems to be okay, but it was the marginal distribution on the `scope` variable that was off (in the original model I posted)

**Comment by stuhlmueller** [comment]
I think this has to do with the fact that, when `Enumerate` "moves on" to an execution with a different value for the `state` variable, it re-creates the `state` object, whereas it's shared between executions that represent different values of `scope` (for the same state), and so only one possible value for `scope` ends up getting used per value for `state`. (I could be wrong—what exactly is going on depends on the enumeration strategy and when exactly values are copied.)

**Comment by hawkrobe** [comment]
I think this is subsumed under #626?

**Comment by null-a** [comment]
This is probably just paraphrasing Andreas, but here's my attempt at explaining this:

It's not the case the each time we sample `state` we get a fresh object. In fact, the execution of two different paths through the program that sample the same `state` will add the same object to the marginal. This sharing means that when `extend` mutates a `state` it doesn't just change the `scope` for the thing we're about to add to the marginal, it changes it for values returned by previous executions too.

@mhtess: Does that help? It seems like everything is working here, so if you're happy I think we can close this. (As @hawkrobe points out, issue #626 covers the question of whether or not it's a good idea to make methods like this available.)

**Comment by mhtess** [comment]
Yes that makes sense
