### ISSUE TITLE
webppl.org redesign/re-branding?

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#691]
I like the simplicity and friendliness of the current webppl.org design (and the interactive code editor front-and-center is awesome). But I also feel like the current design might be under-selling what WebPPL is capable of, especially the description of it as "a small but feature-rich" language. That may have been true of the original dippl-era implementation, but I'd argue that it's not really "small" anymore. Basically, I think that the current website presents the language as more 'toy' than it really is.

Some suggestions for low-effort changes that I think would improve WebPPL's public image:
 - New tagline (i.e. instead of "small but feature-rich")
 - Small section emphasizing what features the language has. Could include the inference algorithms it supports, nested inference, etc.
 - Small section playing up other nice properties of the language, like that you can run it in either the browser or node, and that it plays nicely with existing libraries in the excellent npm ecosystem.

Also open to other suggestions for what people would like to see!

**Comment by longouyang** [comment]
I think having more impressive interactive demos would be really helpful, e.g., the inverse physics example from probmods or a procedural graphics example.

**Comment by stuhlmueller** [comment]
We could also add that it now supports both inference and learning, and show some examples.

**Comment by ngoodman** [comment]
i think this is a great idea. any volunteers to make it happen?

adding a couple of really cool examples (either on the main page or on separate examples pages) would help a lot....

**Comment by stuhlmueller** [comment]
I'm happy to help with this, especially the part where we need to adapt the current html/css/js. Would be great to do examples and other new content collaboratively!

**Comment by ngoodman** [comment]
maybe we can brainstorm (here or elsewhere) some cool examples we could do?

-some kind of procedural graphics
-captcha breaking
-some kind of natural language understanding (pragmatics, semantic parsing, puns?)
-VAE variants on mnist
...

**Comment by stuhlmueller** [comment]
- agents - planning as inference
- lda
- some example that uses data generated in the browser; maybe something [like this](https://stuhlmueller.org/smartpages/)

**Comment by dritchie** [comment]
Probably wouldn't be too hard to get the vines program from the NIPS paper working on the website.

As for the VAE idea: IMO, this is currently probably too slow to train in-browser. But now that I think about it, it might be neat to send already-trained parameters to the client, and then run the learned model / inference network in-browser.

**Comment by stuhlmueller** [comment]
Would be cool to do vines on the page content, maybe using [html2canvas](http://html2canvas.hertzen.com/examples.html) first to get an image of the page.

**Comment by longouyang** [comment]
> As for the VAE idea: IMO, this is currently probably too slow to train in-browser. But now that I think about it, it might be neat to send already-trained parameters to the client, and then run the learned model / inference network in-browser.

For the summer school VAE MNIST classification demo, I used something like this strategy -- train offline, compute KNN for classification, and ship the KNN data to the client for fast classification. This ended up being kind of heavyweight, as there's a ton of KNN data (~2mb), but I think this would be much more viable with a different classification strategy, like random forests.

**Comment by longouyang** [comment]
Also: should we time the rebranding to coincide with a 1.0 release?

One argument against this is that 1.0 might be arbitrarily far away, as it depends on solving some thorny issues (e.g., the dreaded 358). Although an argument for this timing is that it might motivate us to get 1.0 out the door sooner.

While we're on the topic of a 1.0, we seemed to have accumulated a bunch of small issues since the summer school -- maybe we could have a bug-a-thon to quash these?

**Comment by dritchie** [comment]
I went ahead and got started on this in a new branch:

https://github.com/probmods/webppl/tree/gh-pages-redesign

The demos page is currently empty. Feel free to add stuff to it. For the time being, I'm thinking that having all demos on one page would be good, so that viewers get a quick visual overview of all the cool things webppl can do (unless that slows load time to an unacceptable degree). Thoughts? Comments?

**Comment by dritchie** [comment]
FYI, just rearranged things to have a more fully-fleshed out "publications" section.
