### ISSUE TITLE
Provide Dist object corresponding to uniformDraw

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#707]
There was a discussion of this in the Slack channel a while back, and the new PR allowing Categorical to have vectors or unnormalized probs reminded me of it. I think the consensus idea was to have Categorical default to uniform when `ps` isn't provided.

> robert_hawkins: We have `uniformDraw` as a sampling helper, but there’s no corresponding distribution object that you can call `sample` on, or look up scores in. To get this kind of behavior (mostly for pedagogical purposes), I’m having to use the `Categorical` distribution, but it’s a bit messier:

```{js}
var actionPrior = Categorical({vs: ['a', 'b', 'c', 'd'], ps: [1/4, 1/4, 1/4, 1/4]}
sample(actionPrior)
```

> vs

```{js}
var actionPrior =<XYZ>(['a', 'b', 'c', 'd'])
sample(actionPrior)
```

> ndg: i agree there should be some Dist object corresponding to `uniformDraw`, and i like the idea of just having `Categorical` do that when `ps` isn't provided. any objections?

>paul: this seems ok to me in principle. a couple things come to mind: 1) `Categorical` does some serialization internally, which is presumably slower than what `uniformDraw` does. (this may not matter of course.) 2) i think dist constructors check that all params described in the dist meta data are given. this system would need extending to handle optional params.

**Comment by JsonFreeman** [comment]
My current workaround is `Categorical({ vs: array, ps: ones([array.length]).toFlatArray() })`. This is ugly but at least you don't need to write all the probabilities in.
