### ISSUE TITLE
Add webppl to npm

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#71]
...so that it can be installed using `npm install webppl`. This should be set up such that, after `npm install -g webppl`, the `webppl` command is globally available.

**Comment by wuxianliang** [comment]
If there is a Meteor package, it would be great.

**Comment by stuhlmueller** [comment]
I have never used meteor, but if someone wants to follow [this procedure for packaging third-party libraries](http://www.meteorpedia.com/read/Packaging_existing_Libraries), I have no objections.

**Comment by wuxianliang** [comment]
@stuhlmueller  Following an existing package I upload a meteor package for compiling .wppl to .js on the server side and am planning to try calling webppl functions in existing Meteor Apps. Thank you for great work and open mind.
