### ISSUE TITLE
Mixture distribution primitives

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#713]
Normally, a mixture distribution can be expressed via a simple webppl program (first choose the mixture component, then sample from that component). However, there are (at least) a couple scenarios where having a "primitive" mixture distribution comes in handy:

1. The 'enumerating out' trick for reducing variance of the ELBo estimator only works with discrete mixtures. For continuous mixtures (such as GMMs), users have to do the marginalization manually. It'd be nice if this was taken care of automatically.
2. Using mixture distributions as guides (e.g. guiding a `Gaussian` with a `GaussianMixture`, b/c the posterior may be multimodal). This was useful in the neurally-guided procedural modeling work.

There may be other ways to achieve these two goals, but having primitive mixture distribution types seems like the most direct way.

For the NGPM demo I'm building right now, I'm just adding a `GaussianMixture` distribution, but it would be nice to build a more general-purpose constructor that takes a base distribution type and builds a mixture distribution out of it (also: I'd like if my demo ran under "real" webppl, and not my hacked-up version). This would either be callable in webppl code (i.e. a higher-order distribution constructor), or we'd have an npm post-install step that would statically create all the potentially useful mixture types. Thoughts on which is preferable?

**Comment by null-a** [comment]
> Thoughts on which is preferable?

My first thought is that I like the composability of the higher order constructor -- we might use it to do things like mixtures of marginals, etc. And I guess we'd be able to have helpers for making the common combinations, so we don't loose out on usability? (I suppose the *helpers* could be statically generated if we wanted lots of them.) What are the upsides of directly generating the mixtures statically?

**Comment by dritchie** [comment]
Yeah, the "mixture of marginals" idea occurred to me recently as well, so I think the higher-order constructor is the way to go. Statically generating helpers for common cases might be nice, though.

What should the interface for this constructor look like? I was initially thinking it would take a primitive constructor and return a mixture constructor (e.g. something like `FiniteMixture(Gaussian)`, but this wouldn't support the mixture-of-marginals pattern. Now I'm thinking that the constructor ought to take a list of distributions and a list of weights, and just construct the mixture distribution directly. This might necessitate a fair amount of 'type-checking' (making sure all dists have the same support, etc.)

Thoughts?

**Comment by ngoodman** [comment]
how hard would it be to get this to work in "pure webppl"? ie if you try to build a mixture using Infer? maybe what's needed is a sensible way of aggregating Dists when they are the return value of the model in Infer?

**Comment by dritchie** [comment]
As I understand it, building *continuous* mixtures with `Infer` is problematic b/c those marginals only do approximate sampling and scoring. What we want is a distribution that "enumerates out" the discrete mixture component choice but that still uses exact sampling/scoring within that enumeration. I agree, it'd be cool if we could do this in "pure webppl," but AFAIK none of the existing constructs make it possible.

**Comment by ngoodman** [comment]
yeah, i think you're right that existing code wouldn't work to make a gaussian mixture... The right thing may be to add a generic operator that pushes a distribution on distributions on X down to a distribution on X. (i believe this operator is always defined for polish spaces.)

something like:

~~~
var model = function(){return flip()?Gaussian(0,1):Gaussian(5,1)}
var mixture = PushDown( Infer({.., model}) )
~~~

the `PushDown` operator may require a computable equality check on distributions though...

**Comment by dritchie** [comment]
Yeah, I think it would require equality checking. It's easy to see how that would work for primitives (same type, same parameters), but marginals are trickier...

Here's an idea: I imagine that, internally, `PushDown` would essentially perform enumeration to compute weights for each possible return distribution. It would then construct a new distribution given that weighted set of return dists. Why not write that "dist from weighted dists" constructor and expose it to the user for the time being? If we do eventually figure out a nice way to write `PushDown`, we can then add that as an additional layer of abstraction.
