### ISSUE TITLE
Export squishToProbSimplex

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#755]
This happens to be accessible from webppl as `dists.squishToProbSimplex`, but it would be better somewhere else.

**Comment by stuhlmueller** [comment]
Why it's better to make it available as a webppl function: the current exported version can't be used in all contexts that a webppl function can be used. For example, it can't directly be used in `stack([squishToProbsimplex, ...])`, only if it's wrapped in a webppl function like this:

~~~~{js}
var squishToProbSimplex = function(x) {
  return dists.squishToProbSimplex(x);
}
~~~~

This is issue #30.

**Comment by null-a** [comment]
For now, I've added wrappers for this (and `softmax`) to webppl-nn.

(BTW, doing so [got me thinking](https://github.com/null-a/webppl-nn/commit/ef586ef26952e19f08c7c06837680969d1b553a3#diff-04c6e90faac2675aa89e2176d2eec7d8) about whether it makes sense more sense to use `softmax` over `squishToProbSimplex` in the presence of regularization?)
