### ISSUE TITLE
Add file-based param store backend

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#768]
To simplify single-process parameter optimization with persistence across runs, it could be useful to have a param store backend that reads from a file on startup, behaves like the in-memory store at runtime, and writes to the same file on shutdown.

**Comment by null-a** [comment]
@stuhlmueller: I have a WIP version of this [here](https://github.com/probmods/webppl/compare/dev...null-a:file-param-store). I'd be interested in hearing any thoughts you have about the general direction. It includes some documentation which hopefully explains what it does, but let me know if it's unclear.

**Comment by stuhlmueller** [comment]
Nice! Looks to me like it's ready to be merged.
