### ISSUE TITLE
Don't support empty batches with mapData

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#780]
This doesn't seem very useful, whereas not supporting it might catch mistakes in program code.

**Comment by null-a** [comment]
Previous [discussion](https://github.com/probmods/webppl/pull/775#discussion_r101902652).

**Comment by stuhlmueller** [comment]
It makes sense to me that we might want to support empty data arrays. Currently, we're [throwing an error](https://github.com/probmods/webppl/blob/0756b3d14f31941bbaf0c94926b7ab015644b513/src/headerUtils.js#L137) if `batchSize` is greater than the data length, so supporting empty data arrays requires allowing `batchSize` 0. We might want to distinguish a batch size that is automatically computed based on an empty data array from the case where the array is non-empty and the user (perhaps accidentally) specifies batch size 0.
