### ISSUE TITLE
observe should take options to pass on to sample

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#787]
I find myself using this replacement for `observe` all the time:

```js
var observe = function(dist, val) {
  if (val !== undefined) {
    factor(dist.score(val));
    return val;
  } else {
    return sample(dist, { guide() {
      return dist;  // don't use auto-guide; don't complain about no guide
    }});
  }
};
```

It would be preferable to do the same thing via options passed to built-in `observe`.

**Comment by dritchie** [comment]
Seconded; I also use this pattern a lot.

**Comment by stuhlmueller** [comment]
Implementing this might be as simple as (doing the Javascript equivalent of):

```js
var observe = function(dist, val, options) {
  if (val !== undefined) {
    factor(dist.score(val));
    return val;
  } else {
    return sample(dist, options);
  }
};
```

**Comment by stuhlmueller** [comment]
This matters especially if you want to use a model for dream as well. There, you need to use the built-in `observe`, so can't overwrite it as shown above, but if you do use it, you get an auto-guide during ELbo. (Too bad this issue already existed—I was looking forward to creating one titled "Can't observe in dream without guide".)
