### ISSUE TITLE
non-integral poisson deviates w. mean > 10

### ISSUE THREAD

**Issue by al-sharp** [probmods/webppl#824]
`poisson( { mu: Mu } )` for Mu > 10 seems to yield some non-integer deviates.  WebPPL v0.9.7
Fractional residues suggest maybe a type conversion issue?  10 is a threshold in the gen code...

```
var poissonC = function() {
    return poisson( {mu: 11 } );
}
repeat( 10, poissonC )
```
>> [ 12.625, 12.625, 6, 9, 9, 5, 7, 14.625, 5, 9 ]

**Comment by null-a** [comment]
Thanks for reporting this. [GSL](https://github.com/ampl/gsl/blob/d3d2aee48c83d611764ae7a1a2b78df2dc6736af/randist/poisson.c#L33) implements the same algorithm. It looks like we might be missing a `Math.floor` from [here](https://github.com/probmods/webppl/blob/b1d0b58efc5c871979550601cc32f191165a7048/src/dists.ad.js#L1276). I'll work on a fix.

**Comment by longouyang** [comment]
Paul, if you keep the same sampling procedure, could you add a comment saying that this method comes from Ahrens and Dieters' 1974 paper? The title is "Computer Methods for Sampling from Gamma, Beta, Poisson and Binomial Distributions" and the method is called Method PG (page 240)
