### ISSUE TITLE
node scripts/adify && node scripts/distHeader

### ISSUE THREAD

**Issue by hanksohota** [probmods/webppl#841]
npm install -g webppl

sh: 1: node: not found
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "webppl"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! webppl@0.9.7 postinstall: `node scripts/adify && node scripts/distHeader`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webppl@0.9.7 postinstall script 'node scripts/adify && node scripts/distHeader'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webppl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/adify && node scripts/distHeader

**Comment by hanksohota** [comment]
All issues resolved by using the latest versions of git (2.11.0), node.js (7.9.0) and npm (4.5.0).

**Comment by null-a** [comment]
> All issues resolved

Thanks for the update.
