### ISSUE TITLE
using multiple runs of Infer to reduce bias in posterior

### ISSUE THREAD

**Issue by mcusi** [probmods/webppl#855]
Hi,
I have a fairly complex model for which MCMC inference tends to get stuck in (structurally) different modes, including ones I think are reasonable and ones I think are not. Do you have any advice about how I could use multiple runs of Infer to achieve less biased posterior samples? I imagine it could be helpful to swap proposals between different parallel runs but, without that, is there any principled way that I can just compare the scores of the different traces myself, and use that to select between them? I've read through the relevant parts of DIPPL but I'm not confident with the math behind MCMC in spaces of varying dimensions, so any advice at all would be appreciated.
Thanks,
Maddie

**Comment by null-a** [comment]
You can get your hands on the scores of accepted samples by looking at the `samples` property of the marginal distribution returned by `Infer`. For example:

```js
var model = function() {
  return gaussian(0,1)
};
Infer({model, method: 'MCMC', samples: 3}).samples
```

```
[{"value":0.7914576653437873,"score":-1.232141151220392,
{"value":0.4014767687851162,"score":-0.9995303311417415,
{"value":0.8194101622204675,"score":-1.2546550401797592}]
```

These are comparable across runs, so doing as you suggest sounds reasonable to me. Of course, if you never switch modes, you'll never capture the full posterior this way, but depending on what you're trying to achieve this might be acceptable. (Caution, I'm not an expert, so take this advice with a pinch of salt :))

BTW, if you use R, you might be interested in [rwebppl](https://github.com/mhtess/rwebppl), as it has some support for running multiple MCMC chains that you might find convenient.

**Comment by mcusi** [comment]
Thanks, I didn't realize you could access the samples that way. However, I thought you couldn't compare scores when the number of random choices is different, for instance:

```javascript
var model = function() {
  var x = flip()
  if(x) {flip()}
  return x
}

Infer({method:'MCMC', samples:6, lag:1000}, model)
```
with output:

```
dist:
{"probs":[0.5,0.5],"support":[false,true]}
dist.samples:
[{"value":false,"score":-0.6931471805599453},
{"value":false,"score":-0.6931471805599453},
{"value":true,"score":-1.3862943611198906},
{"value":false,"score":-0.6931471805599453},
{"value":true,"score":-1.3862943611198906},
{"value":true,"score":-1.3862943611198906}]

```

Do you know if there's a way to account for a different number of random choices? thanks :)

**Comment by null-a** [comment]
To clarify, `score` is not the log prob of `value` under the marginal distribution on return values (i.e. the distribution returned by `Infer`). Rather, it's the log of the joint probability of all random choices made during that particular execution of the program.

You can see this more clearly if you return the value of both random choices from the program:

```js
var model = function() {
  var x = flip()
  return x ? [x,flip()] : [x];
}

Infer({model: model, method:'MCMC', samples:10}).samples

// [{"value":[false],"score":-0.6931471805599453},
// {"value":[false],"score":-0.6931471805599453},
// {"value":[true,true],"score":-1.3862943611198906},
// {"value":[true,false],"score":-1.3862943611198906},
// {"value":[true,false],"score":-1.3862943611198906}]
```

Does that help?

**Comment by null-a** [comment]
I'm closing this, but feel free to open another issue for further discussion.
