### ISSUE TITLE
Document ERPs (Possibly automatically.)

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#87]
like [webchurch](https://github.com/probmods/webchurch)

**Comment by null-a** [comment]
Somewhat related: IncrementalMH [could use](https://github.com/probmods/webppl/blob/7883e70896184b7ef1e2b564fd6c8fbb5c2cbe07/src/transforms/caching.js#L12) the ability to reflect on available ERPs.

**Comment by stuhlmueller** [comment]
We could use [dox](https://github.com/tj/dox) for this.

**Comment by null-a** [comment]
We probably want to wait until #246 and #268 and done or abandoned.

**Comment by ngoodman** [comment]
@null-a do we now (with new distribution creation interface) have the meta-info that would make docs easy?

**Comment by null-a** [comment]
> do we now (with new distribution creation interface) have the meta-info that would make docs easy?

No, but the distributions are written in such a way that adding it should be pretty straight-forward. I'm expecting that figuring out how to pull the info out and get it into the docs will take at least as long and adding the meta-info.

**Comment by null-a** [comment]
Added by #427.
