### ISSUE TITLE
Strange behavior of methods

### ISSUE THREAD

**Issue by fredcallaway** [probmods/webppl#878]
When I call a method (a function in an object), a function is returned rather than the expected value. The problem is solved by first extracting the function into a separate var. What's going on here?

```js
var addOne = function(x) {
  return x + 1
};

var prm = {f: addOne, arg: 1};
console.log(prm.f(prm.arg))  // -> [Function]
var g = prm.f;
console.log(g(prm.arg))  // -> 2
```

**Comment by stuhlmueller** [comment]
It's this long-standing issue: #358
