### ISSUE TITLE
Visualization tools (for ERPs)

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#88]
It would be nice to have a standard viz library that makes pretty visualizations of common inference results. At the moment ERPs as return values are plotted as barplots. This isn't always appropriate, and sometimes you want to explicitly control the visualizations a bit.

We could do some smarter/prettier default plotting based on the domain of the ERP: if real plot density and truehist, if objects plot facetted field marginals and scatters, etc.

For example:
~~~
var erp = Enumerate(function(){return flip(0.5);})
viz.plot(erp)
~~~
should make a barplot as it does now. But:
~~~
var erp = Enumerate(function(){return gaussian(0.5);})
viz.plot(erp)
~~~
should make a density + truhist plot, with x-axis domain set to account for most of probability mass.
~~~
var erp = Enumerate(function(){
  var x = flip(0.5);
  var y = flip(x?0.9:0.3);
  return {"X": x, "Y": y};})
viz.plot(erp)
~~~
could make a facetted plot showing the marginal over X, marginal over Y, and some representation of the joint distribution like the scatter of expected X vs expected Y. (extra credit if the plots are linked so that clicking a point in the scatter highlights the corresponding bars in the marginals!)

On the other hand, sometimes you want to say more explicitly what plot to draw. For the above example, if i want a 2d density plot of XvsY i should be able to say something like `viz.density(erp, "x", "y").

This all could be implemented on top of vega.js (or d3.js).

**Comment by hawkrobe** [comment]
+1 on this. Especially for Bayesian data analysis, it's pretty essential to be able to examine the full posterior for continuous variables. I might tackle this for an upcoming hackathon.

**Comment by hawkrobe** [comment]
@feste just told me she has a basic line plot implementation in dimple, which raises a question: where should we put visualization tools? I see three options.

1. Keep it all in the dippl repo, where the current bar plot print functionality lives. The obvious downside is that we may want to use these tools elsewhere.
2. Create an 'online' subdirectory within the webppl repo, define a viz module in there, and import that module when webppl is loaded in the browser. This mimics the webchurch setup, I believe.
3. Create a separate vizppl repo, possibly shared between webchurch and webppl (and whatever future languages might want to visualize distributions in the browser).

The final option sounds like the most forward-thinking to me, and is more in the node.js style of splitting off dependencies into separate modules. What do you think?

**Comment by stuhlmueller** [comment]
I like the third option, too. This will serve as an example of creating (sub-)packages for webppl, which is a problem that deserves a good solution more generally. (We encountered a similar situation for coarse-to-fine. Currently, coarse-to-fine requires webppl as a subpackage, but that's not quite right.)

**Comment by longouyang** [comment]
webppl-viz is fairly stable now, so we can close this
