### ISSUE TITLE
Trouble installing globally

### ISSUE THREAD

**Issue by beansbeansbeans** [probmods/webppl#887]
Hello,

I was able to `npm install webppl` in a project, but when I tried to install globally, I got the following error:

/usr/local/bin/webppl -> /usr/local/lib/node_modules/webppl/webppl

webppl@0.9.10 postinstall /usr/local/lib/node_modules/webppl
node scripts/adify && node scripts/distHeader

fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/webppl/src/aggregation/ScoreAggregator.js'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /usr/local/lib/node_modules/webppl/scripts/adify:38:6
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/webppl/scripts/adify:35:37)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webppl@0.9.10 postinstall: `node scripts/adify && node scripts/distHeader`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webppl@0.9.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Do you know what this could be about?

Thank you!
Ann

**Comment by null-a** [comment]
> Do you know what this could be about?

Once the WebPPL package is installed, we run a script via npm's 'postinstall' hook that generates some additional code. The error above appears to be happening because this script doesn't have permission to write these files under '/usr/local/lib/node_modules/webppl'. TBH, I don't understand why the install works but the script doesn't.

As a workaround, perhaps you could try changing into '/usr/local/lib/node_modules/webppl' and running `npm run postinstall` with `sudo`?

**Comment by beansbeansbeans** [comment]
Hmm, but the `webppl` directory gets removed when the postinstall fails? Sorry if I'm being naive about this. 

At any rate it's not a big deal - I just installed webppl locally to a repo and am smoothly running it from the command line there :)

Thanks for the response!

**Comment by null-a** [comment]
> the webppl directory gets removed when the postinstall fails

Ah, I didn't realise that.

> Sorry if I'm being naive about this.

Not at all!

**Comment by null-a** [comment]
It looks like `npm install` takes a `--ignore-scripts` command line argument, so if you do want to get the global install working, perhaps you could use that and *then* try my work around.

**Comment by beansbeansbeans** [comment]
Hey that worked! Thanks a lot! 🍻

**Comment by x-ji** [comment]
I also encountered this issue. Mac OS 10.13, node v6.10.1, npm 5.4.2

**Comment by null-a** [comment]
@x-ji Thanks for letting us know.
