### ISSUE TITLE
Bug in `factor`

### ISSUE THREAD

**Issue by esdu** [probmods/webppl#889]
Hello, I'm not sure if this actually a bug with `factor`, or with something more fundamental.

I'm messing around with http://probmods.org/chapters/03-conditioning.html , and I was trying to run:

```
var dist = Infer({method: 'enumerate'},
  function () {
    var A = flip() + 1
    factor(A*A)
    return A
});
print(dist)
viz(dist)
```
<img width="808" alt="screen shot 2017-10-09 at 8 45 31 pm" src="https://user-images.githubusercontent.com/817420/31364464-d87375b6-ad32-11e7-8279-b4ad6eadbf35.png">

Which is correct, (0.9525741268224333/0.04742587317756678 = Math.exp(4)/Math.exp(1))

However, if I simply replace `A*A` by `A^2`, the result is backwards:
```
var dist = Infer({method: 'enumerate'},
  function () {
    var A = flip() + 1
    factor(A^2)
    return A
});
print(dist)
viz(dist)
```
<img width="806" alt="screen shot 2017-10-09 at 8 47 38 pm" src="https://user-images.githubusercontent.com/817420/31364508-1e653ca8-ad33-11e7-923b-608bee56fa05.png">

Any idea what's going on here?

**Comment by hawkrobe** [comment]
The caret `^` is bitwise XOR in javascript:

https://stackoverflow.com/questions/9768393/what-does-the-caret-symbol-do-in-javascript

if you want to take a power, use `Math.pow(A, 2)`
