### ISSUE TITLE
Global install fails with restricted permissions

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#891]
Our post install script can fail in some situations.  See #887. ~As discussed in that issue, a workaround is to install with the `npm` flag `--ignore-scripts`, and then run the scripts with appropriate permissions manually, using something like `(sudo) npm run postinstall`.~ (See below for a simpler workaround.)

**Comment by null-a** [comment]
It appears that post install scripts are run with [restricted privileges](https://docs.npmjs.com/misc/scripts#user). This behaviour can be suppressed, suggesting the following (simpler) workaround:

```
npm install -g webppl --unsafe-perm
```

I've not tried this, so I'd be interesting to hear how it works out from anyone who does.

**Comment by jfkominsky** [comment]
I used the command in oct. 23 comment after repeated failures with the postinstall script. The new command (run with sudo) worked without any problems at all, and webppl seems to be operational.

**Comment by null-a** [comment]
@jfkominsky Great, thanks for updating the issue with this info.

**Comment by chrisbrickhouse** [comment]
I also used the above work around on Ubuntu 17.10 (with sudo) and it installed without a problem.

**Comment by null-a** [comment]
A potential long term fix is to apply the ad transform to `*.ad.js` files using a [`prepublish`](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) rather than a `postinstall` script. I will try to take a closer look at this soon.

> As an interim solution, perhaps the readme should just be updated?

@jkhartshorne Thanks for the update. This is a good idea -- if we don't come up with a permanent solution soon, we should do this.
