### ISSUE TITLE
.MAP().val incorrect?

### ISSUE THREAD

**Issue by daphnab** [probmods/webppl#897]
Calling `.MAP()` on a distribution generated by `Infer` seems to produce incorrect results (I couldn't find documentation for this call, but it's currently used in several examples in the Bayesian Data Analysis chapter and exercises of the probmods book). 

Here is a test demonstrating the behavior (and suggesting that the call may be returning just a random sample, although a consistent random sample for a given distribution instance). 

~~~~javascript
var a1 = 20
var b1 = 5

var a2 = 1
var b2 = 2

//As long as first beta is peakier
var trueMAP = (a1 - 1)/(a1 + b1 - 2);

var trueMean = (1/(1 + (b1/a1)) + 1/(1 + (b2/a2)))/2

print("true MAP: " + trueMAP)
print("true mean: " + trueMean)

var model = function()
{
  return flip () ? beta(a1, b1) : beta(a2, b2)
}

var MAPTest = function()
{
  var opts = {method: "rejection", samples: 1000};
  var d = Infer(opts, model);
  var map_sqerr = Math.pow((d.MAP().val - trueMAP), 2)
  var sample_sqerr = Math.pow((sample(d) - trueMAP),2)
  var est_mean = expectation(d)
  var mean_sqerr = Math.pow((est_mean - trueMean),2)
  return {MAP: d.MAP().val, map_sqerr: map_sqerr, 
          sample_sqerr: sample_sqerr, est_mean: est_mean,
         est_mean_sqerr: mean_sqerr}
}

print("ORIGINAL DISTRIBUTION")
var opts = {method: "rejection", samples: 10000};
var d = Infer(opts, model);
viz(d)
print("MAP estimate: " + d.MAP().val)
print("MAP estimate: " + d.MAP().val)
print("MAP estimate: " + d.MAP().val)

print("DISTRIBUTION OF MAP AND MEAN ESTIMATES")
var opts = {method: "rejection", samples: 1000};
var mapDist = Infer(opts, MAPTest);

print("mean estimated MAP: " + expectation(marginalize(mapDist, "MAP")))
print("MSE MAP estimate: " + expectation(marginalize(mapDist, "map_sqerr")))
print("MSE random sample: " + expectation(marginalize(mapDist, "sample_sqerr")))

//Just for sanity checking
print("expectation of the mean: " + expectation(marginalize(mapDist, "est_mean")))
print("MSE mean: " + expectation(marginalize(mapDist, "est_mean_sqerr")))

viz.marginals(mapDist)
~~~~

**Comment by hawkrobe** [comment]
see also #140 (rejection just returns a histogram of samples and for continuous params it probably never returns the exact same sample more than once, so all values in the posterior will have the same score)

**Comment by mhtess** [comment]
it's probable that the usage of MAP in the BDA chapter is not optimal. should investigate switching to `expectation`

**Comment by null-a** [comment]
@daphnab I'm guessing that @hawkrobe is correct, and that this is an instance of #140, so I'll close this issue in favour of that one. Feel free to re-open if not, of course.

**Comment by ngoodman** [comment]
Yeah... MAP isn’t documented because it isn’t officially supported because it is generally a Dangerous and Fallible thing. It’s much better to use an expectation. (And we should change the BDA chapter accordingly.)
