### ISSUE TITLE
Syntax errorr: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chagag** [probmods/webppl#898]
Hi, I am trying to upload a dataset and come up with the error above.
This happens both when running it in webppl.org and on my computer. 

Any suggestions?  

This is the data- 
var data = {
  "1": [-4, -2, -8, -18, -24, -16, -12, 4, 2, 0, -20, -22],
  "2": [16, 22, 12, 0, 4, -2, -4, 8, 18, 24, 20, 2],
  "3": [0, -2, 2, -18, -20, -8, 4, -16, -22, -4, -24, -12],
  "4": [-8, 14, 2, -10, -14, -12, 10, -6, 8, 12, -2, 6],
  "5": [4, 18, 24, 22, 16, -4, 12, 20, -2, 2, 8, 0],
  "6": [0, -8, -12, 2, 4, -18, -24, -16, -2, -4, -20, -22],
  "7": [18, 20, 0, 24, -2, 16, 4, 12, -4, 22, 8, 2],
  "8": [20, 22, -2, 12, 4, 16, 2, 18, 8, 24, -4, 0],
  "9": [0, -2, 16, 8, 22, 2, 4, 20, -4, 12, 24, 18],
  "10": [12, 10, 2, -12, -6, -10, -8, 6, 14, -2, 8, -14],
  "11": [6, -15, 9, -8, 9, -16, 7, 9, -11, -2, 4, 8],
  "12": [18, 20, 24, 8, 2, -2, 0, 12, 4, 22, -4, 16],
  "13": [-2, 6, 12, -14, 2, -12, -8, -6, 14, -10, 10, 8],
  "14": [3, 5, -5, -18, -15, -4, 2, -20, -18, -20, -9, -22],
  "15": [-14, 8, 14, 12, -6, -12, -10, 2, 10, -2, -8, 6],
  "16": [15, -8, 12, -10, -5, 13, 6, -10, -8, 5, 1, -10],
  "17": [4, 9, -2, 6, -11, -16, 9, -15, -8, 8, 7, 9],
  "18": [6, 5, 12, -8, -10, -8, -10, -10, 13, -5, 15, 1],
  "19": [8, 14, -6, 6, -14, -8, -2, -12, 2, 12, 10, -10],
  "20": [6, -10, -12, -8, 10, -2, 12, -14, 8, -6, 2, 14],
  "21": [-1, -6, 19, 19, 2, 8, -5, 14, 17, 19, 18, 16],
  "22": [0, 2, -20, -24, -8, -18, -12, 4, -22, -16, -4, -2],
  "23": [-5, -10, -8, 12, -10, 5, 6, -10, 13, 1, 15, -8],
  "24": [13, 12, -8, -8, -10, 1, 15, -5, 6, -12, 5, -10],
  "25": [6, 5, 1, 15, -10, -8, -5, -10, 12, -8, -10, 13],
    "10a": [12, 10, 2, -12, -6, -10, -8, 6, 14, -2, 8, -14],
  "11a": [6, -15, 9, -8, 9, -16, 7, 9, -11, -2, 4, 8],
  "12a": [18, 20, 24, 8, 2, -2, 0, 12, 4, 22, -4, 16],
  "13a": [-2, 6, 12, -14, 2, -12, -8, -6, 14, -10, 10, 8],
  "14a": [3, 5, -5, -18, -15, -4, 2, -20, -18, -20, -9, -22],
  "15a": [-14, 8, 14, 12, -6, -12, -10, 2, 10, -2, -8, 6],
  "16a": [15, -8, 12, -10, -5, 13, 6, -10, -8, 5, 1, -10],
  "17a": [4, 9, -2, 6, -11, -16, 9, -15, -8, 8, 7, 9],
  "18a": [6, 5, 12, -8, -10, -8, -10, -10, 13, -5, 15, 1],
  "19a": [8,14, -6, 6, -14, -8, -2, -12, 2, 12, 10, -10],
  "20a": [6, -10, -12, -8, 10, -2, 12, -14, 8, -6, 2, 14],
  "21a": [-1, -6, 19, 19, 2, 8, -5, 14, 17, 19, 18, 16],
  "22a": [0, 2, -20, -24, -8, -18, -12, 4, -22, -16, -4, -2],
  "23a": [-5, -10, -8, 12, -10, 5, 6, -10, 13, 1, 15, -8],
  "24a": [13, 12, -8, -8, -10, 1, 15, -5, 6, -12, 5, -10],
  "25a": [6, 5, 1, 15, -10, -8, -5, -10, 12, -8, -10, 13]
}

data

**Comment by null-a** [comment]
Interesting! I'm seems like this has something to do with parsing large array/object literals, and I'd guess it's a bug in WebPPL. As a work around, you could represent your data as a giant string and parse it with `JSON.parse`. Something like:

```js
var data = '{"1": [1,2,3], "2": [4,5,6]}'
JSON.parse(data)
```

If you are only working at the command line, then you could use the [`webppl-json`](https://github.com/stuhlmueller/webppl-json) package to replace the giant string with a file on disk.

**Comment by chagag** [comment]
Thanks!
