### ISSUE TITLE
Unexpected behavior with arrays of functions

### ISSUE THREAD

**Issue by ftc** [probmods/webppl#907]
I have found two cases where an array of functions does not behave correctly.  The first is when selecting a function from an array with a categorical distribution.  The second is related to immediately invoking a function dereferenced from an array. I believe they are likely related.

```
var a = [function(){return 1}, function(){return 2}]
var b = sample(Categorical({ps:[1,1],vs:a}))
b()
```
Expected output:
1 or 2

Actual output:
always 1

```
var a = [function(){return 1}, function(){return 2}]
a[0]()
```

Expected output (this is the behavior of node.js):
1

Actual output:
[function]

Note that the following behaves correctly:

```
var a = [function(){return 1}, function(){return 2}]
var b = a[0]
b()
```

Thanks!

**Comment by null-a** [comment]
I think this is essentially an instance of #179. The problem arises from the use of `JSON.stringify` (in the implementation of `Categorial`) to compare the elements of `vs`.

A work around might be to sample an index from a `Discrete`, and use the result to grab the function out of the array, something like:

```js
var a = [function(){return 1}, function(){return 2}]
var b = a[sample(Discrete({ps: [1,1]}))]
b()
```

**Comment by ftc** [comment]
Thank you for the response.  This certainly seems like a reasonable workaround and is pretty close to what I ended up doing.  Please let me know if there is anything more I can provide to help work out these issues. I will post any more details I find.
