### ISSUE TITLE
Does `LogNormal` already exist?

### ISSUE THREAD

**Issue by erindb** [probmods/webppl#910]
We have `LogitNormal` and its multivariate generalization `LogisticNormal`, but I can't find `LogNormal`. Am I just not looking correctly? or does it actually not exist? If it doesn't exist, I'm happy to implement it. I think it would be useful for people (like me) who sometimes forget that the Log-Normal density function at x isn't just the Normal density function evaluated at log(x). (Doh!)

**Comment by null-a** [comment]
No, there isn't a `LogNormal` at present. Here are a few pointers that might help make the process of adding a new distribution go a little smoother, or at least help you get started, should you choose to add one.

- Distributions live [here](https://github.com/probmods/webppl/tree/dev/src/dists). There's one file per distribution. Any new distribution would also need adding to `index.ad.js` in the same directory.
- These are `*.ad.js` files, so during development you'll need to run `grunt build` to transform them to `*.js`. See these [docs](http://docs.webppl.org/en/master/development/workflow.html#modifying-ad-js-files).
- `grunt build` also automatically creates the sampling helper functions. e.g. It creates the `gaussian(..)` helper, which is short for `sample(Gaussian(...))`.
- The documentation for a distribution exists as properties on the distribution object itself. Running `grunt generate-docs` will extract this and update the documentation. This needs to be run manually once the distribution's docs are finalized, and the resulting changes to [this file](https://github.com/probmods/webppl/blob/dev/docs/primitive-distributions.txt) should be committed to the repo.
- The `base` and `transform` properties of a distribution are how we implement the reparameterization trick for variational inference. These could be omitted initially.
- See e.g. `gamma.ad.js` for how to indicate that the log normal has bounded support. (This information is used by the HMC sampler.)
- There's some infrastructure for testing samplers/scorers [here](https://github.com/probmods/webppl/tree/dev/tests), see `test-samples.js` and `test-scoreres.js`. I'm only pointing this out in case it's useful. Not all samplers are exercised by this yet, and I've not used it myself.

I'm happy to expand on this, answer other questions, etc. Good luck!

**Comment by ngoodman** [comment]
@null-a those are awesome pointers! maybe add them to the readme (or some dev docs linked from there) for future reference?
