### ISSUE TITLE
Nested map and reduce

### ISSUE THREAD

**Issue by sanitgupta** [probmods/webppl#923]
```
var scr = 
    map(function(dee) {
    var z = reduce(function(x, acc) { return x + acc; }, 0, 
    map(function(obs) 
    {
    dee.score(obs);
    }, set));
    return z;}, dist);
```

In this code, if instead of creating a variable z, I return the reduce function directly, I get an empty value in scr. Creating the variable z helps me avoid the issue and scr gets the correct value.
Again, not sure if this is a bug or if I am misunderstanding something.

**Comment by null-a** [comment]
Please post a minimal example the reproduces the problem that I can run, and I'll take a look. Thanks!

**Comment by sanitgupta** [comment]
Sorry, I tried to reproduce the error and was unable to. I must have made a mistake.

**Comment by null-a** [comment]
No problem!
