### ISSUE TITLE
get statistics from RVs

### ISSUE THREAD

**Issue by lukas1994** [probmods/webppl#932]
I want to run simulations and get certain statistics about some marginal distributions.
Say I have a program like
```
var model = function() {
  var x = gaussian(0,1);
  var y = x + gaussian(0,1);
  return [x,y];
}
Infer({method: 'forward', samples: 10000, model});
```
I'm running it in the browser  and I want to calculate the p5, mean, p95 of x. What's the best way to do that? Should I just take the samples from the output distribution and calculate it myself? How do I take the `score` into account? Or is it recommended to stay inside the PPL environment and do the calculations there (I saw you have an `expectation()` function).

What docs can you recommend? I've found various things like `param()` that wasn't in the docs?

**Comment by lukas1994** [comment]
cc @null-a

**Comment by null-a** [comment]
> What's the best way to do that? 

As you noted, we already have an `expectation` helper, which is just a regular WebPPL function. I'd suggest writing similar functions for the other statistics you require, as those aren't in core WebPPL. `expectation` is written in terms of the `.support()` and `.score(val)` (log prob) methods (which are available on all distributions that have finite support), and I think you'll be able to do something similar. If you take a look at the [implementation](https://github.com/probmods/webppl/blob/daabd60361f72eef53f69005751facce34c7f916/src/header.wppl#L136-L142) I think you'll get the idea. Let me know if not.

> I've found various things like param() that wasn't in the docs?

See [here](http://docs.webppl.org/en/master/optimization/parameters.html).
