### ISSUE TITLE
Is there a forum or help desk to ask some beginner questions?

### ISSUE THREAD

**Issue by ljlin** [probmods/webppl#939]
Hello WebPPL team,

I was wondering if I have some beginner questions, such as the following one, where should I go to ask? 

> How to get a plot that reasonably approximates the unit uniform distributed by inferring the `simple_model` ?
> ```js
> var simple_model = function() {
>   var z = sample(Uniform({a: 0, b: 1}))
>   return z
> }
> var dist = Infer({
>   method: 'SMC', 
>   particles: 100, 
>   rejuvSteps: 5,
>   model : simple_model
> })
> 
> viz.auto(dist)
> ```

Thanks.

**Comment by null-a** [comment]
Hi. 

> I was wondering if I have some beginner questions, such as the following one, where should I go to ask?

I suggest using the [mailing list](https://groups.google.com/forum/#!forum/webppl-dev). Don't be put off my the name, it's not only for WebPPL development. Sadly, the list doesn't see much traffic, but I'm subscribed and I'll try to help if I can.

> How to get a plot that reasonably approximates the unit uniform distributed by inferring the simple_model ?

Depending on which aspect of the plot you're not happy with, maybe try increasing the number of samples, or switching from the density plot (that `viz.auto` is giving you) to a histogram (using `viz.hist`).

FWIW, I'd probably just use `{method: 'rejection', samples: 10000, ...}` for something like this. SMC + rejuvenation will give you correct results, but it's a roundabout way of collecting samples from a model like this. (Though the overhead is probably pretty small.)
