### ISSUE TITLE
Refactor tests: run all inference algorithms on a core set of models

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#94]
This will help us check that inference implementations don't forget handle some basic constructs (like structure change).

**Comment by null-a** [comment]
I've made a start on this. The basic approach is to split apart the model definitions and inference procedures [like so](https://github.com/null-a/webppl/commit/e1a4e159e67e24690f278086b5299d6ab0c41d31#diff-e0a743b6daf0785c82a7f8635fffc632R10).

One problem with this is that I'll end up duplicating the models currently in `examples`, though not having the test suite depend in stuff in `examples` might be a good thing.

Feedback welcome!

**Comment by null-a** [comment]
I've done a little more on this, it's currently on a branch in my fork:

https://github.com/null-a/webppl/commits/refactor-inference-tests

**Comment by null-a** [comment]
This now includes all of the tests currently specified by `tests/test-data/models/*.wppl`.

The new test runner allows us to specify models, inference algorithms, and which combinations of the two to test. Adding additional models which we test all inference algorithms against should be straight-forward.

The intention is that it's also possible to add tests of the type mentioned in #66. I've added [testing of the normalization constant](https://github.com/probmods/webppl/commit/69a5b319ad50b28aba91bf33c4842c9ec3aa5caa) as an example.

**Comment by stuhlmueller** [comment]
Looks good to me. I don't think it's a problem that we're decoupling examples and tests again, even if it leads to some duplication for now. It would be good to still run all the examples as part of the CI tests, even if we don't check their return distribution, to at least verify that changes don't break any of the examples in obvious ways.
