### ISSUE TITLE
REPL shell ?

### ISSUE THREAD

**Issue by vsraptor** [probmods/webppl#941]
Is there a REPL shell  for webppl ?

**Comment by null-a** [comment]
I'm afraid not. The closest thing is perhaps the web notebook on e.g. https://webppl.org.

**Comment by vsraptor** [comment]
> I'm afraid not. The closest thing is perhaps the web notebook on e.g. https://webppl.org.

what about "node" .. is there a way to shoehorn it somehow

**Comment by null-a** [comment]
If you wanted to implement this yourself, you might need to think about how WebPPL's somewhat functional nature interacts with a REPL's somewhat imperative nature. The [global store](https://webppl.readthedocs.io/en/master/globalstore.html) might come in here? I've never put any thought into doing this though, so I don't have anything more concrete to suggest I'm afraid.
