### ISSUE TITLE
Add rejection sampling

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#96]
Requires an upper bound on the total factor score per execution (easiest is 0, with restriction to negative factor values).

**Comment by null-a** [comment]
Have I understood this correctly:

It's tricky to reject samples early without the restriction that factor values are all negative. With such a restriction, once `scoreSoFar` drops below the `logUniform + maxScore` threshold no future `factor` statements can rescue the execution. When positive factor values are allowed, it's hard to say anything useful about what the rest of the program will do, so we'd have to run it to the end before deciding whether to accept or reject.

I've played with the current code a little. I noticed that we need to `JSON.stringify` the properties of `hist`, but other than that it seemed to be working OK. What's broken about it?

**Comment by stuhlmueller** [comment]
As I understand it, for rejection to work, you need an upper bound on the total achievable factor score (`maxScore` in my code; this can be 0 when all factors are negative). This allows you to reject traces based on how far below `maxScore` their score is. The simplest way to implement this is to do a single big rejection step at the end. I tried to be clever and do early rejection, but I think my math is broken and so the resulting distributions aren't right in general. (I haven't spent much time on this -- let me know if I should look into this and fix it.)
